### ISSUE TITLE
Error installing os-provided python

### ISSUE THREAD

**Issue by chrmarti** [devcontainers/features#110]
@samruddhikhandale @joshspicer 

`find` passes its results on to `xargs` in a way that breaks when the paths contain spaces:
https://github.com/devcontainers/features/blob/ec1deb82808c14de9ce601838e255357718b49d4/src/python/install.sh#L391

I see this fail using the following with 0.248.0:
```json
{
    "image": "mcr.microsoft.com/vscode/devcontainers/base:0-bullseye",
    "features": {
       "node": "latest",
       "python": "os-provided"
    } 
}
```

https://unix.stackexchange.com/questions/172481/how-to-quote-arguments-with-xargs suggests using `find` with `-print0` and `xargs` with `-0` to use `\0` as the delimiter. (This seems to work for our case too based on a quick try.)

Similarly:
https://github.com/devcontainers/features/blob/ec1deb82808c14de9ce601838e255357718b49d4/src/python/install.sh#L411

```
[12 ms] Remote-Containers 0.248.0 in VS Code 1.71.0-insider (235a92a3693176fbf9af16ec5b829c458a1d682f).
[...]
#0 11.32 Skipping apt-get update.
#0 11.33 Reading package lists...
#0 11.60 Building dependency tree...
#0 11.66 Reading state information...
#0 11.73 python3 is already the newest version (3.9.2-3).
#0 11.73 python3 set to manually installed.
#0 11.73 The following additional packages will be installed:
#0 11.73   blt libjs-jquery libjs-sphinxdoc libjs-underscore libpython3-dev
#0 11.73   libpython3.9 libpython3.9-dev python-pip-whl python3-distutils
#0 11.73   python3-lib2to3 python3-pkg-resources python3-setuptools python3-wheel
#0 11.73   python3.9-dev python3.9-doc python3.9-venv tk8.6-blt2.5
#0 11.74 Suggested packages:
#0 11.74   blt-demo python3-examples python-setuptools-doc tix python3-tk-dbg
#0 11.74 Recommended packages:
#0 11.74   javascript-common build-essential
#0 11.87 The following NEW packages will be installed:
#0 11.87   blt libjs-jquery libjs-sphinxdoc libjs-underscore libpython3-dev
#0 11.87   libpython3.9 libpython3.9-dev python-pip-whl python3-dev python3-distutils
#0 11.87   python3-doc python3-lib2to3 python3-pip python3-pkg-resources
#0 11.87   python3-setuptools python3-tk python3-venv python3-wheel python3.9-dev
#0 11.87   python3.9-doc python3.9-venv tk8.6-blt2.5
#0 11.93 0 upgraded, 22 newly installed, 0 to remove and 9 not upgraded.
#0 11.93 Need to get 21.2 MB of archives.
#0 11.93 After this operation, 90.4 MB of additional disk space will be used.
#0 11.93 Get:1 http://deb.debian.org/debian bullseye/main arm64 tk8.6-blt2.5 arm64 2.5.3+dfsg-4.1 [540 kB]
#0 12.16 Get:2 http://deb.debian.org/debian bullseye/main arm64 blt arm64 2.5.3+dfsg-4.1 [14.9 kB]
#0 12.16 Get:3 http://deb.debian.org/debian bullseye/main arm64 libjs-jquery all 3.5.1+dfsg+~3.5.5-7 [315 kB]
#0 12.20 Get:4 http://deb.debian.org/debian bullseye/main arm64 libjs-underscore all 1.9.1~dfsg-3 [100 kB]
#0 12.22 Get:5 http://deb.debian.org/debian bullseye/main arm64 libjs-sphinxdoc all 3.4.3-2 [127 kB]
#0 12.23 Get:6 http://deb.debian.org/debian bullseye/main arm64 libpython3.9 arm64 3.9.2-1 [1556 kB]
#0 12.36 Get:7 http://deb.debian.org/debian bullseye/main arm64 libpython3.9-dev arm64 3.9.2-1 [3835 kB]
#0 12.60 Get:8 http://deb.debian.org/debian bullseye/main arm64 libpython3-dev arm64 3.9.2-3 [21.7 kB]
#0 12.61 Get:9 http://deb.debian.org/debian bullseye/main arm64 python-pip-whl all 20.3.4-4+deb11u1 [1948 kB]
#0 12.71 Get:10 http://deb.debian.org/debian bullseye/main arm64 python3.9-dev arm64 3.9.2-1 [515 kB]
#0 12.74 Get:11 http://deb.debian.org/debian bullseye/main arm64 python3-lib2to3 all 3.9.2-1 [77.8 kB]
#0 12.74 Get:12 http://deb.debian.org/debian bullseye/main arm64 python3-distutils all 3.9.2-1 [143 kB]
#0 12.75 Get:13 http://deb.debian.org/debian bullseye/main arm64 python3-dev arm64 3.9.2-3 [24.8 kB]
#0 12.75 Get:14 http://deb.debian.org/debian bullseye/main arm64 python3.9-doc all 3.9.2-1 [10.9 MB]
#0 13.33 Get:15 http://deb.debian.org/debian bullseye/main arm64 python3-doc all 3.9.2-3 [21.6 kB]
#0 13.33 Get:16 http://deb.debian.org/debian bullseye/main arm64 python3-pkg-resources all 52.0.0-4 [190 kB]
#0 13.34 Get:17 http://deb.debian.org/debian bullseye/main arm64 python3-setuptools all 52.0.0-4 [366 kB]
#0 13.36 Get:18 http://deb.debian.org/debian bullseye/main arm64 python3-wheel all 0.34.2-1 [24.0 kB]
#0 13.36 Get:19 http://deb.debian.org/debian bullseye/main arm64 python3-pip all 20.3.4-4+deb11u1 [337 kB]
#0 13.38 Get:20 http://deb.debian.org/debian bullseye/main arm64 python3-tk arm64 3.9.2-1 [100 kB]
#0 13.38 Get:21 http://deb.debian.org/debian bullseye/main arm64 python3.9-venv arm64 3.9.2-1 [5396 B]
#0 13.38 Get:22 http://deb.debian.org/debian bullseye/main arm64 python3-venv arm64 3.9.2-3 [1188 B]
#0 13.74 Fetched 21.2 MB in 2s (14.0 MB/s)
#0 13.76 Selecting previously unselected package tk8.6-blt2.5.
(Reading database ... 26073 files and directories currently installed.)
#0 13.77 Preparing to unpack .../00-tk8.6-blt2.5_2.5.3+dfsg-4.1_arm64.deb ...
#0 13.77 Unpacking tk8.6-blt2.5 (2.5.3+dfsg-4.1) ...
#0 13.82 Selecting previously unselected package blt.
#0 13.82 Preparing to unpack .../01-blt_2.5.3+dfsg-4.1_arm64.deb ...
#0 13.82 Unpacking blt (2.5.3+dfsg-4.1) ...
#0 13.84 Selecting previously unselected package libjs-jquery.
#0 13.84 Preparing to unpack .../02-libjs-jquery_3.5.1+dfsg+~3.5.5-7_all.deb ...
#0 13.84 Unpacking libjs-jquery (3.5.1+dfsg+~3.5.5-7) ...
#0 13.88 Selecting previously unselected package libjs-underscore.
#0 13.88 Preparing to unpack .../03-libjs-underscore_1.9.1~dfsg-3_all.deb ...
#0 13.88 Unpacking libjs-underscore (1.9.1~dfsg-3) ...
#0 13.90 Selecting previously unselected package libjs-sphinxdoc.
#0 13.90 Preparing to unpack .../04-libjs-sphinxdoc_3.4.3-2_all.deb ...
#0 13.90 Unpacking libjs-sphinxdoc (3.4.3-2) ...
#0 13.93 Selecting previously unselected package libpython3.9:arm64.
#0 13.93 Preparing to unpack .../05-libpython3.9_3.9.2-1_arm64.deb ...
#0 13.93 Unpacking libpython3.9:arm64 (3.9.2-1) ...
#0 14.04 Selecting previously unselected package libpython3.9-dev:arm64.
#0 14.04 Preparing to unpack .../06-libpython3.9-dev_3.9.2-1_arm64.deb ...
#0 14.04 Unpacking libpython3.9-dev:arm64 (3.9.2-1) ...
#0 14.29 Selecting previously unselected package libpython3-dev:arm64.
#0 14.30 Preparing to unpack .../07-libpython3-dev_3.9.2-3_arm64.deb ...
#0 14.30 Unpacking libpython3-dev:arm64 (3.9.2-3) ...
#0 14.31 Selecting previously unselected package python-pip-whl.
#0 14.32 Preparing to unpack .../08-python-pip-whl_20.3.4-4+deb11u1_all.deb ...
#0 14.32 Unpacking python-pip-whl (20.3.4-4+deb11u1) ...
#0 14.42 Selecting previously unselected package python3.9-dev.
#0 14.42 Preparing to unpack .../09-python3.9-dev_3.9.2-1_arm64.deb ...
#0 14.42 Unpacking python3.9-dev (3.9.2-1) ...
#0 14.44 Selecting previously unselected package python3-lib2to3.
#0 14.44 Preparing to unpack .../10-python3-lib2to3_3.9.2-1_all.deb ...
#0 14.45 Unpacking python3-lib2to3 (3.9.2-1) ...
#0 14.47 Selecting previously unselected package python3-distutils.
#0 14.47 Preparing to unpack .../11-python3-distutils_3.9.2-1_all.deb ...
#0 14.47 Unpacking python3-distutils (3.9.2-1) ...
#0 14.50 Selecting previously unselected package python3-dev.
#0 14.50 Preparing to unpack .../12-python3-dev_3.9.2-3_arm64.deb ...
#0 14.50 Unpacking python3-dev (3.9.2-3) ...
#0 14.52 Selecting previously unselected package python3.9-doc.
#0 14.52 Preparing to unpack .../13-python3.9-doc_3.9.2-1_all.deb ...
#0 14.52 Unpacking python3.9-doc (3.9.2-1) ...
#0 14.92 Selecting previously unselected package python3-doc.
#0 14.92 Preparing to unpack .../14-python3-doc_3.9.2-3_all.deb ...
#0 14.93 Unpacking python3-doc (3.9.2-3) ...
#0 14.95 Selecting previously unselected package python3-pkg-resources.
#0 14.95 Preparing to unpack .../15-python3-pkg-resources_52.0.0-4_all.deb ...
#0 14.95 Unpacking python3-pkg-resources (52.0.0-4) ...
#0 14.98 Selecting previously unselected package python3-setuptools.
#0 14.98 Preparing to unpack .../16-python3-setuptools_52.0.0-4_all.deb ...
#0 14.99 Unpacking python3-setuptools (52.0.0-4) ...
#0 15.02 Selecting previously unselected package python3-wheel.
#0 15.03 Preparing to unpack .../17-python3-wheel_0.34.2-1_all.deb ...
#0 15.03 Unpacking python3-wheel (0.34.2-1) ...
#0 15.05 Selecting previously unselected package python3-pip.
#0 15.05 Preparing to unpack .../18-python3-pip_20.3.4-4+deb11u1_all.deb ...
#0 15.05 Unpacking python3-pip (20.3.4-4+deb11u1) ...
#0 15.09 Selecting previously unselected package python3-tk:arm64.
#0 15.09 Preparing to unpack .../19-python3-tk_3.9.2-1_arm64.deb ...
#0 15.09 Unpacking python3-tk:arm64 (3.9.2-1) ...
#0 15.12 Selecting previously unselected package python3.9-venv.
#0 15.12 Preparing to unpack .../20-python3.9-venv_3.9.2-1_arm64.deb ...
#0 15.12 Unpacking python3.9-venv (3.9.2-1) ...
#0 15.14 Selecting previously unselected package python3-venv.
#0 15.14 Preparing to unpack .../21-python3-venv_3.9.2-3_arm64.deb ...
#0 15.14 Unpacking python3-venv (3.9.2-3) ...
#0 15.16 Setting up python3-pkg-resources (52.0.0-4) ...
#0 15.27 Setting up tk8.6-blt2.5 (2.5.3+dfsg-4.1) ...
#0 15.27 Setting up blt (2.5.3+dfsg-4.1) ...
#0 15.28 Setting up python3-tk:arm64 (3.9.2-1) ...
#0 15.33 Setting up python3-wheel (0.34.2-1) ...
#0 15.41 Setting up libpython3.9:arm64 (3.9.2-1) ...
#0 15.42 Setting up python-pip-whl (20.3.4-4+deb11u1) ...
#0 15.42 Setting up libjs-jquery (3.5.1+dfsg+~3.5.5-7) ...
#0 15.43 Setting up python3-lib2to3 (3.9.2-1) ...
#0 15.48 Setting up libjs-underscore (1.9.1~dfsg-3) ...
#0 15.49 Setting up python3-distutils (3.9.2-1) ...
#0 15.55 Setting up python3-setuptools (52.0.0-4) ...
#0 15.72 Setting up libpython3.9-dev:arm64 (3.9.2-1) ...
#0 15.73 Setting up python3.9-doc (3.9.2-1) ...
#0 15.73 Setting up python3-pip (20.3.4-4+deb11u1) ...
#0 15.87 Setting up libjs-sphinxdoc (3.4.3-2) ...
#0 15.87 Setting up python3.9-dev (3.9.2-1) ...
#0 15.87 Setting up python3.9-venv (3.9.2-1) ...
#0 15.90 Setting up python3-doc (3.9.2-3) ...
#0 15.91 Setting up libpython3-dev:arm64 (3.9.2-3) ...
#0 15.91 Setting up python3-venv (3.9.2-3) ...
#0 15.91 Setting up python3-dev (3.9.2-3) ...
#0 15.92 Processing triggers for man-db (2.9.4-2) ...
#0 15.99 Processing triggers for libc-bin (2.31-13+deb11u3) ...
#0 16.02 Updating /etc/bash.bashrc and /etc/zsh/zshrc...
#0 28.54 chmod: cannot access '/usr/local/share/nvm/test/slow/nvm': No such file or directory
#0 28.54 chmod: cannot access 'use': No such file or directory
#0 28.54 chmod: cannot access '/usr/local/share/nvm/test/slow/nvm': No such file or directory
#0 28.54 chmod: cannot access 'exec': No such file or directory
#0 28.54 chmod: cannot access '/usr/local/share/nvm/test/slow/nvm': No such file or directory
#0 28.54 chmod: cannot access 'run': No such file or directory
#0 28.55 chmod: cannot access '/usr/local/share/nvm/test/slow/nvm': No such file or directory
#0 28.55 chmod: cannot access 'uninstall': No such file or directory
#0 28.55 chmod: cannot access '/usr/local/share/nvm/test/slow/nvm': No such file or directory
#0 28.55 chmod: cannot access 'reinstall-packages': No such file or directory
#0 28.55 chmod: cannot access '/usr/local/share/nvm/test/slow/nvm': No such file or directory
#0 28.55 chmod: cannot access 'reinstall-packages/test-npmlink': No such file or directory
#0 28.55 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.55 chmod: cannot access 'tests': No such file or directory
#0 28.55 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.56 chmod: cannot access 'tests/mocks': No such file or directory
#0 28.56 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.56 chmod: cannot access 'tests/mocks/project_dirs': No such file or directory
#0 28.56 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.56 chmod: cannot access 'tests/mocks/project_dirs/inside-n_m-nested': No such file or directory
#0 28.56 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.56 chmod: cannot access 'tests/mocks/project_dirs/inside-n_m-nested/node_modules': No such file or directory
#0 28.56 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.56 chmod: cannot access 'tests/mocks/project_dirs/inside-n_m-nested/node_modules/foo': No such file or directory
#0 28.56 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.56 chmod: cannot access 'tests/mocks/project_dirs/inside-n_m-nested/node_modules/foo/bar': No such file or directory
#0 28.56 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.57 chmod: cannot access 'tests/mocks/project_dirs/no-nesting-both': No such file or directory
#0 28.57 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.57 chmod: cannot access 'tests/mocks/project_dirs/no-nesting-both/node_modules': No such file or directory
#0 28.57 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.57 chmod: cannot access 'tests/mocks/project_dirs/inside-n_m-nested-pkg': No such file or directory
#0 28.57 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.57 chmod: cannot access 'tests/mocks/project_dirs/inside-n_m-nested-pkg/node_modules': No such file or directory
#0 28.57 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.57 chmod: cannot access 'tests/mocks/project_dirs/inside-n_m-nested-pkg/node_modules/foo': No such file or directory
#0 28.57 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.57 chmod: cannot access 'tests/mocks/project_dirs/inside-n_m-nested-pkg/node_modules/foo/bar': No such file or directory
#0 28.58 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.58 chmod: cannot access 'tests/mocks/project_dirs/nested-both': No such file or directory
#0 28.58 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.58 chmod: cannot access 'tests/mocks/project_dirs/nested-both/a': No such file or directory
#0 28.58 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.58 chmod: cannot access 'tests/mocks/project_dirs/nested-both/a/b': No such file or directory
#0 28.58 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.58 chmod: cannot access 'tests/mocks/project_dirs/nested-both/a/b/c': No such file or directory
#0 28.58 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.58 chmod: cannot access 'tests/mocks/project_dirs/nested-both/a/b/c/d': No such file or directory
#0 28.58 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.58 chmod: cannot access 'tests/mocks/project_dirs/nested-both/node_modules': No such file or directory
#0 28.59 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.59 chmod: cannot access 'tests/mocks/project_dirs/no-nesting-n_m': No such file or directory
#0 28.59 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.59 chmod: cannot access 'tests/mocks/project_dirs/no-nesting-n_m/node_modules': No such file or directory
#0 28.59 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.59 chmod: cannot access 'tests/mocks/project_dirs/no-nesting-pkg': No such file or directory
#0 28.59 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.59 chmod: cannot access 'tests/mocks/project_dirs/nested-pkg': No such file or directory
#0 28.59 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.59 chmod: cannot access 'tests/mocks/project_dirs/nested-pkg/a': No such file or directory
#0 28.59 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.59 chmod: cannot access 'tests/mocks/project_dirs/nested-pkg/a/b': No such file or directory
#0 28.59 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.59 chmod: cannot access 'tests/mocks/project_dirs/nested-pkg/a/b/c': No such file or directory
#0 28.60 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.60 chmod: cannot access 'tests/mocks/project_dirs/nested-pkg/a/b/c/d': No such file or directory
#0 28.60 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.60 chmod: cannot access 'tests/mocks/project_dirs/nested-n_m': No such file or directory
#0 28.60 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.60 chmod: cannot access 'tests/mocks/project_dirs/nested-n_m/a': No such file or directory
#0 28.60 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.60 chmod: cannot access 'tests/mocks/project_dirs/nested-n_m/a/b': No such file or directory
#0 28.60 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.60 chmod: cannot access 'tests/mocks/project_dirs/nested-n_m/a/b/c': No such file or directory
#0 28.60 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.60 chmod: cannot access 'tests/mocks/project_dirs/nested-n_m/a/b/c/d': No such file or directory
#0 28.60 chmod: cannot access '/usr/local/share/nvm/test/fast/Unit': No such file or directory
#0 28.61 chmod: cannot access 'tests/mocks/project_dirs/nested-n_m/node_modules': No such file or directory
#0 28.61 chmod: cannot access '/usr/local/share/nvm/test/fast/Listing': No such file or directory
#0 28.61 chmod: cannot access 'versions': No such file or directory
#0 28.61 chmod: cannot access '/usr/local/share/nvm/test/fast/Listing': No such file or directory
#0 28.61 chmod: cannot access 'paths': No such file or directory
#0 28.61 chmod: cannot access '/usr/local/share/nvm/test/fast/Set': No such file or directory
#0 28.61 chmod: cannot access 'Colors': No such file or directory
------
error: failed to solve: executor failed running [/bin/sh -c cd /tmp/build-features/python_2 && export $(cat devcontainer-features.env | xargs) && chmod +x ./install.sh && ./install.sh]: exit code: 123
[34638 ms] Stop (31462 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/hj/vvzp2ffx69gbfmkhf5tckppm0000gn/T/vsch/container-features/0.248.0-1661172724974 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/base:0-bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-smktst-76fd0a5486a4cde5083a94a3f6598b36-features -f /var/folders/hj/vvzp2ffx69gbfmkhf5tckppm0000gn/T/vsch/container-features/0.248.0-1661172724974/Dockerfile.extended /var/folders/hj/vvzp2ffx69gbfmkhf5tckppm0000gn/T/__dev-containers-build-empty
[34638 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/hj/vvzp2ffx69gbfmkhf5tckppm0000gn/T/vsch/container-features/0.248.0-1661172724974 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/base:0-bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-smktst-76fd0a5486a4cde5083a94a3f6598b36-features -f /var/folders/hj/vvzp2ffx69gbfmkhf5tckppm0000gn/T/vsch/container-features/0.248.0-1661172724974/Dockerfile.extended /var/folders/hj/vvzp2ffx69gbfmkhf5tckppm0000gn/T/__dev-containers-build-empty
[34638 ms]     at pA (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.248.0/dist/spec-node/devContainersSpecCLI.js:255:2186)
[34639 ms]     at vv (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.248.0/dist/spec-node/devContainersSpecCLI.js:255:2124)
[34639 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[34639 ms]     at async SA (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.248.0/dist/spec-node/devContainersSpecCLI.js:261:2006)
[34639 ms]     at async Ms (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.248.0/dist/spec-node/devContainersSpecCLI.js:261:3110)
[34639 ms]     at async bk (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.248.0/dist/spec-node/devContainersSpecCLI.js:366:9409)
[34639 ms]     at async vk (/Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.248.0/dist/spec-node/devContainersSpecCLI.js:366:9165)
[34640 ms] Stop (34356 ms): Run: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.248.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/chrmarti/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/chrmarti/Development/repos/smktst --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/chrmarti/Development/repos/smktst --log-level trace --log-format json --config /Users/chrmarti/Development/repos/smktst/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[34640 ms] Exit code 1
[34641 ms] Command failed: /Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper.app/Contents/MacOS/Code - Insiders Helper /Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.248.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/chrmarti/Library/Application Support/Code - Insiders/User/globalStorage/ms-vscode-remote.remote-containers/data --workspace-folder /Users/chrmarti/Development/repos/smktst --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/chrmarti/Development/repos/smktst --log-level trace --log-format json --config /Users/chrmarti/Development/repos/smktst/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[34641 ms] Exit code 1
```

**Comment by chrmarti** [comment]
Btw., `find` seems to run on `/usr`, so `chmod` will run on all its folders. Is this intended? It goes beyond the feature's own folders.

**Comment by samruddhikhandale** [comment]
> Btw., `find` seems to run on `/usr`, so `chmod` will run on all its folders. Is this intended? It goes beyond the feature's own folders.

That's not intentional, and is a regression. Fixed it in https://github.com/devcontainers/features/pull/112

**Comment by samruddhikhandale** [comment]
Shipped fix 🚀 
https://github.com/devcontainers/features/pkgs/container/features%2Fpython
