### ISSUE TITLE
Java feature sets GRADLE_USER_HOME incorrently

### ISSUE THREAD

**Issue by asaikali** [devcontainers/features#150]
When I install java via the feature it sets the `GRADLE_USER_HOME` env var to `./.gradle` instead of `${HOME}/.gradle` as the code in 
https://github.com/devcontainers/features/blob/b7b5d8b1c02f6a8755c880d6f615115760462c8b/src/java/devcontainer-feature.json#L44 tries to do.

When the devcontainer starts and `./gradlew` is invoked the following exception is produced 
```
./gradlew
Exception in thread "main" java.lang.RuntimeException: Could not create parent directory for lock file /.gradle/wrapper/dists/gradle-7.4.1-bin/58kw26xllvsiedyf3nujyarhn/gradle-7.4.1-bin.zip.lck
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:43)
        at org.gradle.wrapper.Install.createDist(Install.java:62)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)
```

This is because the vscode user in the container does not have permission to create `/.gradle` directory. If i run `unset GRADLE_USER_HOME` things work just fine because it will default to the `.gradle` in the home folder.

**Comment by jkeech** [comment]
@samruddhikhandale can you take a look?

**Comment by samruddhikhandale** [comment]
PR for the bug fix - https://github.com/devcontainers/features/pull/152
