### ISSUE TITLE
Error: Failed to process feature ghcr.io/devcontainers/features/docker-from-docker:1

### ISSUE THREAD

**Issue by tepene** [devcontainers/features#151]
I can't install the docker-from-docker feature. I tried the configuration snippet provided in the [README](https://github.com/devcontainers/features/tree/main/src/docker-from-docker#example-usage).

```json
  "features": {
    "ghcr.io/devcontainers/features/docker-from-docker:1": {
      "version": "latest"
    }
  }
```

When building the the devcontainer i get the error **Error: Failed to process feature ghcr.io/devcontainers/features/docker-from-docker:1**

```bash
[2022-09-13T12:12:14.568Z] * Processing feature: ghcr.io/devcontainers/features/docker-from-docker:1
[2022-09-13T12:12:14.604Z] Failed to get registry auth token with error: Error: read ECONNRESET
[2022-09-13T12:12:14.614Z] (!) WARNING: Falling back to deprecated GitHub Release syntax. See https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#referencing-a-feature for updated specification.
[2022-09-13T12:12:14.614Z] Github feature.
[2022-09-13T12:12:14.614Z] Invalid parse for GitHub Release feature: Follow format '<publisher>/<feature-set>/<feature>, or republish feature to OCI registry.'
[2022-09-13T12:12:14.615Z] Error: Failed to process feature ghcr.io/devcontainers/features/docker-from-docker:1
[2022-09-13T12:12:14.616Z]     at QR (/home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:188:2956)
[2022-09-13T12:12:14.616Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-09-13T12:12:14.616Z]     at async uc (/home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:188:2279)
[2022-09-13T12:12:14.616Z]     at async Zs (/home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:188:12771)
[2022-09-13T12:12:14.616Z]     at async OF (/home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:257:3261)
[2022-09-13T12:12:14.616Z]     at async Wf (/home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:257:2801)
[2022-09-13T12:12:14.617Z]     at async pb (/home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:257:1779)
[2022-09-13T12:12:14.617Z]     at async DF (/home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:263:2006)
[2022-09-13T12:12:14.617Z]     at async to (/home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:263:3110)
[2022-09-13T12:12:14.617Z]     at async Ak (/home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js:383:8108)
[2022-09-13T12:12:14.619Z] Stop (402 ms): Run: /usr/share/code/code --ms-enable-electron-run-as-node /home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/oizlus/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path /usr/bin/docker --workspace-folder /home/oizlus/Code/cmp-sdlc.stzh.ch/cisco_aci_operation --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/oizlus/Code/cmp-sdlc.stzh.ch/cisco_aci_operation --log-level debug --log-format json --config /home/oizlus/Code/cmp-sdlc.stzh.ch/cisco_aci_operation/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-13T12:12:14.620Z] Exit code 1
[2022-09-13T12:12:14.629Z] Command failed: /usr/share/code/code --ms-enable-electron-run-as-node /home/oizlus/.vscode/extensions/ms-vscode-remote.remote-containers-0.251.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /home/oizlus/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --docker-path /usr/bin/docker --workspace-folder /home/oizlus/Code/cmp-sdlc.stzh.ch/cisco_aci_operation --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/oizlus/Code/cmp-sdlc.stzh.ch/cisco_aci_operation --log-level debug --log-format json --config /home/oizlus/Code/cmp-sdlc.stzh.ch/cisco_aci_operation/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-13T12:12:14.629Z] Exit code 1
```
Building the devcontainer without the feature is successful.

**Comment by samruddhikhandale** [comment]
Hi @tepene, I just tried out the dev container config, and it worked for me without any errors.

> Failed to get registry auth token with error: Error: read ECONNRESET

Looking at the logs, I can see the `ECONNRESET ` error, could it be possible that there was a network connection failure or a VPN / firewall trying to interfere?

**Comment by tepene** [comment]
@samruddhikhandale, thanks for the tip. I just verified that it is working on my private workstation. Looks indeed like a proxy issue. I misinterpreted the error message.
