### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by li-sumup** [devcontainers/features#186]
I am using default Debian with terraform and git enabled:
```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the README at:
// https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/debian
{
	"name": "Debian",
	"build": {
		"dockerfile": "Dockerfile",
		// Update 'VARIANT' to pick an Debian version: bullseye, buster
		// Use bullseye on local arm64/Apple Silicon.
		"args": {
			"VARIANT": "bullseye"
		}
	},
	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],
	// Uncomment to use the Docker CLI from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker.
	// "mounts": [ "source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind" ],
	// Uncomment when using a ptrace-based debugger like C++, Go, and Rust
	// "runArgs": [ "--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined" ],
	// Comment out to connect as root instead. More info: https://aka.ms/vscode-remote/containers/non-root.
	"remoteUser": "vscode",
	"features": {
		"terraform": "latest",
		"git": "latest"
	}
}
```

```dockerfile
# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.245.2/containers/debian/.devcontainer/base.Dockerfile

# [Choice] Debian version (use bullseye on local arm64/Apple Silicon): bullseye, buster
ARG VARIANT="buster"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}

# ** [Optional] Uncomment this section to install additional packages. **
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
```

And I am getting error:

```logs
[2022-09-27T06:43:40.890Z] * Processing feature: terraform
[2022-09-27T06:43:41.513Z] * Fetching feature: terraform_1_oci
[2022-09-27T06:45:53.490Z] error: Error: connect ETIMEDOUT 198.51.44.1:443
[2022-09-27T06:45:53.491Z] (!) ERR: Failed to fetch feature: Failed to download package for ghcr.io/devcontainers/features/terraform 
[2022-09-27T06:45:54.668Z] Error: Failed to download package for ghcr.io/devcontainers/features/terraform
[2022-09-27T06:45:54.669Z]     at M0 (/home/lukas/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:155:7434)
[2022-09-27T06:45:54.669Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-09-27T06:45:54.670Z]     at async nF (/home/lukas/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:188:7406)
[2022-09-27T06:45:54.671Z]     at async uc (/home/lukas/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:188:2448)
[2022-09-27T06:45:54.671Z]     at async Zs (/home/lukas/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:188:12771)
[2022-09-27T06:45:54.671Z]     at async OF (/home/lukas/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:257:3261)
[2022-09-27T06:45:54.671Z]     at async Wf (/home/lukas/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:257:2801)
[2022-09-27T06:45:54.672Z]     at async pb (/home/lukas/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:257:1779)
[2022-09-27T06:45:54.672Z]     at async DF (/home/lukas/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:263:2006)
[2022-09-27T06:45:54.672Z]     at async to (/home/lukas/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js:263:3110)
[2022-09-27T06:45:54.676Z] Stop (132837 ms): Run in Host: /home/lukas/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7/node /home/lukas/.vscode-remote-containers/dist/dev-containers-cli-0.251.0/dist/spec-node/devContainersSpecCLI.js up --workspace-folder /home/lukas/projects/github-settings --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-20.04\home\lukas\projects\github-settings --log-level debug --log-format json --config /home/lukas/projects/github-settings/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2022-09-27T06:45:54.677Z] Exit code 1
```

I was able to run similar configuration before, but now building fails.

I am running VSCode from WSL2
<img width="285" alt="image" src="https://user-images.githubusercontent.com/98388748/192455384-b9f44554-cabf-48e1-92ef-70d0fde7ec18.png">

**Comment by jasper2virtual** [comment]
I have a similar issue too, my office behind proxy, suddenly today it always timeout on fetching feature.....

**Comment by samruddhikhandale** [comment]
Looks like the issue is related with https://github.com/microsoft/vscode-remote-release/issues/7150

Feel free to re-open the issue if the problem resurfaces, thanks!
