### ISSUE TITLE
Failed to download package for ghcr.io/devcontainers/features/azure-cli 

### ISSUE THREAD

**Issue by johnnyreilly** [devcontainers/features#221]
I might be being terribly unlucky, but I keep getting timeouts when I try to download the azure-cli feature.  Is this an issue with GitHub packages or is this a general problem?

```
[132380 ms] * Processing feature: ghcr.io/devcontainers/features/azure-cli:1
[132999 ms] * Fetching feature: azure-cli_1_oci
[165788 ms] error: Error: connect ETIMEDOUT 205.251.192.181:443
[165788 ms] (!) ERR: Failed to fetch feature: Failed to download package for ghcr.io/devcontainers/features/azure-cli 
[165788 ms] Error: Failed to download package for ghcr.io/devcontainers/features/azure-cli
    at YP (/home/johnnyreilly/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1729:9596)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ise (/home/johnnyreilly/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1787:8267)
    at async dm (/home/johnnyreilly/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1787:2465)
    at async _ae (/home/johnnyreilly/.vscode-remote-containers/dist/dev-containers-cli-0.255.3/dist/spec-node/devContainersSpecCLI.js:1994:26640)
[165792 ms] Exit code 1
```

My `devcontainer.json` looks like this:

```json
"features": {
		"ghcr.io/devcontainers/features/azure-cli:1": {
			"version": "latest"
		}
	}
```

**Comment by sas05** [comment]
i have tried git and aws-cli, also same error.

**Comment by joshspicer** [comment]
Are you all continuing to see this?  It seems like a transient Packages issue to me (and I haven't noticed it myself/am not able to reproduce a couple days later).  

Please give me a tag if you continue to see this and i'll dig in further

**Comment by johnnyreilly** [comment]
Thanks - will check again some time this week and report if issues

**Comment by sas05** [comment]
after some query, I have found this ticket. I think it is related to this problem. https://github.com/microsoft/vscode-remote-release/issues/7150

**Comment by samruddhikhandale** [comment]
Feel free to re-open the issue if the problem resurfaces.

**Comment by mataslib** [comment]
I am getting this error when connected to university eduroam wifi. On other wifis no issue.

**Comment by jufuju** [comment]
What rights does directory _vscode-dev-containers_ have? 
You should set the rights _drwxr--r--_ under /home/username/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/node_modules/vscode-dev-containers
