### ISSUE TITLE
dotnet CLI feature is installed with wrong permissions

### ISSUE THREAD

**Issue by salvador-barboza** [devcontainers/features#293]
Hello devcontainers team,

I was using the dotnet CLI feature, and when running `dotnet restore` on my Codespace, it throws the following error:
```
System.UnauthorizedAccessException: Access to the path '/home/codespace/.dotnet/7.0.100.toolpath.sentinel' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode, Func`4 createOpenException)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, UnixFileMode openPermissions, Int64& fileLength, UnixFileMode& filePermissions, Func`4 createOpenException)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Create(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean isDotnetBeingInvokedFromNativeInstaller, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider, Dictionary`2 performanceMeasurements)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, TimeSpan startupTime, ITelemetry telemetryClient)
```

Repro steps:
1) Create a Codespace with the dotnet cli feature (https://github.com/codespaces/new/?repo=salvador-barboza/blankie&ref=dotnet-restore-issue)
2) Run dotnet restore in the terminal

**Comment by jungaretti** [comment]
It looks like this is still a problem

**Comment by deesejohn** [comment]
Similar issue here, but with `dotnet restore`. I was able to resolve the issue via:

```
sudo mkdir -p ~/.local/share/NuGet/
sudo chown $USER ~/.local/share/NuGet/
```
