### ISSUE TITLE
 Could not resolve Feature

### ISSUE THREAD

**Issue by pieterv-icloud-com** [devcontainers/features#392]
Just got back from leave and tried rebuilding my devcontainers, but it looks like there is something going wrong when processing features.

Looks like an auth issue with github:

```
devcontainer build . --verbose
(node:72793) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code Helper --trace-deprecation ...` to show where the warning was created)
[25 ms] @devcontainers/cli 0.25.2. Node.js v16.14.2. darwin 19.6.0 x64.
[24 ms] Start: Run: docker buildx version
[838 ms] Stop (814 ms): Run: docker buildx version
[838 ms] github.com/docker/buildx v0.9.1 ed00243a0ce2a0aee75311b06e32d33b44729689
[839 ms]
[851 ms] Start: Run: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/base:0-bullseye
[936 ms] Stop (85 ms): Run: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/base:0-bullseye
[939 ms] local container features stored at: /Users/pietervandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/node_modules/vscode-dev-containers/container-features
[940 ms] Start: Run: tar --no-same-owner -x -f -
[979 ms] Stop (39 ms): Run: tar --no-same-owner -x -f -
[979 ms] workspace root: /Users/pietervandermerwe/repos/roslyn-observability
[991 ms] Loaded /Users/pietervandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/node_modules/vscode-dev-containers/container-features/devcontainer-features.json, which declares 25 features and does not contain explicit source info.
[991 ms] --- Processing User Features ----
[992 ms] * Processing feature: ghcr.io/devcontainers/features/aws-cli:1
[992 ms] > input: ghcr.io/devcontainers/features/aws-cli:1
[992 ms] >
[992 ms] > resource: ghcr.io/devcontainers/features/aws-cli
[992 ms] > id: aws-cli
[993 ms] > version: 1
[993 ms] > owner: devcontainers
[993 ms] > namespace: devcontainers/features
[993 ms] > registry: ghcr.io
[993 ms] > path: devcontainers/features/aws-cli
[993 ms] manifest url: https://ghcr.io/v2/devcontainers/features/aws-cli/manifests/1
[994 ms] url: https://ghcr.io/token?scope=repository:devcontainers/features/aws-cli:pull&service=ghcr.io
[1629 ms] HTTP request failed with status code 403: : Forbidden
[1630 ms] Failed to get registry auth token with error: Error: HTTP 403: Forbidden
[2207 ms] (!) WARNING: Falling back to deprecated GitHub Release syntax. See https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#referencing-a-feature for updated specification.
[2207 ms] Github feature.
[2207 ms] Could not resolve Feature 'ghcr.io/devcontainers/features/aws-cli:1'.  Ensure the Feature is published and accessible from your current environment.
Error: Failed to process feature ghcr.io/devcontainers/features/aws-cli:1
    at Pse (/Users/pietervandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1805:3150)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Sm (/Users/pietervandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1805:2294)
    at async Jf (/Users/pietervandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1807:1415)
    at async Doe (/Users/pietervandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:2580)
    at async EF (/Users/pietervandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:1893:1978)
    at async fue (/Users/pietervandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:19430)
    at async lue (/Users/pietervandermerwe/.vscode/extensions/ms-vscode-remote.remote-containers-0.266.1/dist/spec-node/devContainersSpecCLI.js:2020:17550)
{"outcome":"error","message":"Failed to process feature ghcr.io/devcontainers/features/aws-cli:1","description":"An error occurred building the container."}
```

**Comment by pieterv-icloud-com** [comment]
This is pretty embarrassing, turns out my github token expired and I had to create a new one.
