### ISSUE TITLE
Dev containers with Features are failing to build

### ISSUE THREAD

**Issue by pamelafox** [devcontainers/features#432]
So far, I have tried three different Python repos, and all are failing to build in Codespaces today. They previously worked for me.

For example:
https://github.com/pamelafox/simple-flask-server-example

The final error relates to features, that's why I'm sharing it here:

```
{"outcome":"error","message":"Failed to process feature ghcr.io/devcontainers/features/python:1","description":"An error occurred setting up the container."}
```

It's possible the actual error is earlier in the process however.

```
Configuration starting...
Using image: mcr.microsoft.com/devcontainers/universal:2
Creating container...
$ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --skip-non-blocking-commands --skip-post-create --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell
[264 ms] @devcontainers/cli 0.28.0. Node.js v14.21.2. linux 5.4.0-1100-azure x64.
[7329 ms] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=bind,src=/var/lib/docker/codespacemount/workspace,dst=/workspaces --mount type=volume,src=dind-var-lib-docker-0hcbhh2c7vldoj773drm1bjldnb89u0rt96sl9nju22d9ou8d14n,dst=/var/lib/docker --mount type=volume,src=minikube-config,dst=/home/vscode/.minikube --mount source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind --mount source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind --mount source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind --mount source=/mnt/containerTmp,target=/tmp,type=bind --mount type=bind,src=/.codespaces/agent/mount/cache,dst=/vscode -l Type=codespaces -e CODESPACES=true -e ContainerVersion=12 -u codespace --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --privileged --init --label CodespacesImageType=Default --label ContainerVersion=12 --hostname codespaces-95ca49 --add-host codespaces-95ca49:127.0.0.1 --cap-add sys_nice --network host --label IsWarmUpContainer=true --init --privileged --cap-add SYS_PTRACE --security-opt seccomp=unconfined --entrypoint /bin/sh -l devcontainer.metadata=[{"id":"ghcr.io/devcontainers/features/common-utils:2"},{"id":"ghcr.io/devcontainers/features/dotnet:1"},{"id":"ghcr.io/devcontainers/features/hugo:1"},{"id":"ghcr.io/devcontainers/features/node:1"},{"id":"./local-features/nvs"},{"id":"ghcr.io/devcontainers/features/python:1"},{"id":"./local-features/machine-learning-packages"},{"id":"ghcr.io/devcontainers/features/php:1"},{"id":"ghcr.io/devcontainers/features/conda:1"},{"id":"ghcr.io/devcontainers/features/ruby:1"},{"id":"ghcr.io/devcontainers/features/java:1"},{"id":"ghcr.io/devcontainers/features/sshd:1","entrypoint":"/usr/local/share/ssh-init.sh"},{"id":"ghcr.io/devcontainers/features/git-lfs:1"},{"id":"ghcr.io/devcontainers/features/github-cli:1"},{"id":"ghcr.io/devcontainers/features/docker-in-docker:2","privileged":true,"entrypoint":"/usr/local/share/docker-init.sh","mounts":[{"source":"dind-var-lib-docker-${devcontainerId}","target":"/var/lib/docker","type":"volume"}]},{"id":"ghcr.io/devcontainers/features/kubectl-helm-minikube:1","mounts":[{"source":"minikube-config","target":"/home/vscode/.minikube","type":"volume"}]},{"id":"ghcr.io/devcontainers/features/go:1","init":true,"capAdd":["SYS_PTRACE"],"securityOpt":["seccomp=unconfined"]},{"id":"./local-features/jekyll"},{"id":"ghcr.io/devcontainers/features/oryx:1"},{"id":"./local-features/setup-user"},{"customizations":{"vscode":{"settings":{"go.toolsManagement.checkForUpdates":"local","go.useLanguageServer":true,"go.gopath":"/go","python.defaultInterpreterPath":"/home/codespace/.python/current/bin/python3","python.formatting.autopep8Path":"/usr/local/py-utils/bin/autopep8","python.formatting.blackPath":"/usr/local/py-utils/bin/black","python.formatting.yapfPath":"/usr/local/py-utils/bin/yapf","python.linting.banditPath":"/usr/local/py-utils/bin/bandit","python.linting.flake8Path":"/usr/local/py-utils/bin/flake8","python.linting.mypyPath":"/usr/local/py-utils/bin/mypy","python.linting.pycodestylePath":"/usr/local/py-utils/bin/pycodestyle","python.linting.pydocstylePath":"/usr/local/py-utils/bin/pydocstyle","python.linting.pylintPath":"/usr/local/py-utils/bin/pylint","jupyter.kernels.filter":[{"path":"/opt/conda/bin/python","type":"pythonEnvironment"},{"path":"/usr/local/python/current/bin/python3","type":"pythonEnvironment"},{"path":"/usr/local/python/current/bin/python","type":"pythonEnvironment"},{"path":"/usr/bin/python3","type":"pythonEnvironment"},{"path":"/bin/python3","type":"pythonEnvironment"}],"lldb.executable":"/usr/bin/lldb"},"extensions":["GitHub.vscode-pull-request-github"]}},"containerUser":"codespace","remoteUser":"codespace"},{"customizations":{"vscode":{"settings":{"go.toolsManagement.checkForUpdates":"local","go.useLanguageServer":true,"go.gopath":"/go","python.defaultInterpreterPath":"/home/codespace/.python/current/bin/python3","python.formatting.autopep8Path":"/usr/local/py-utils/bin/autopep8","python.formatting.blackPath":"/usr/local/py-utils/bin/black","python.formatting.yapfPath":"/usr/local/py-utils/bin/yapf","python.linting.banditPath":"/usr/local/py-utils/bin/bandit","python.linting.enabled":true,"python.linting.flake8Path":"/usr/local/py-utils/bin/flake8","python.linting.mypyPath":"/usr/local/py-utils/bin/mypy","python.linting.pycodestylePath":"/usr/local/py-utils/bin/pycodestyle","python.linting.pydocstylePath":"/usr/local/py-utils/bin/pydocstyle","python.linting.pylintEnabled":true,"python.linting.pylintPath":"/usr/local/py-utils/bin/pylint","jupyter.kernels.filter":[{"path":"/opt/conda/bin/python","type":"pythonEnvironment"},{"path":"/bin/python2","type":"pythonEnvironment"},{"path":"/usr/bin/python2","type":"pythonEnvironment"},{"path":"/usr/local/python/current/bin/python3","type":"pythonEnvironment"},{"path":"/usr/local/python/current/bin/python","type":"pythonEnvironment"},{"path":"/usr/bin/python3","type":"pythonEnvironment"},{"path":"/bin/python3","type":"pythonEnvironment"}],"lldb.executable":"/usr/bin/lldb"}}},"mounts":["source=/root/.codespaces/shared,target=/workspaces/.codespaces/shared,type=bind","source=/var/lib/docker/codespacemount/.persistedshare,target=/workspaces/.codespaces/.persistedshare,type=bind","source=/.codespaces/agent/mount,target=/.codespaces/bin,type=bind","source=/mnt/containerTmp,target=/tmp,type=bind"],"containerEnv":{"CODESPACES":"true","ContainerVersion":"12"},"remoteUser":"codespace","remoteEnv":{"CLOUDENV_ENVIRONMENT_ID":"a3ef4e4c-3596-48ab-8b17-cfb2152106e4"},"overrideCommand":false}] mcr.microsoft.com/devcontainers/universal:2 -c echo Container started
Container started
Outcome: success User: codespace WorkspaceFolder: /workspaces/workspace
devcontainer process exited with exit code 0
Running blocking commands...
$ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --skip-non-blocking-commands --expect-existing-container --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell
[373 ms] @devcontainers/cli 0.28.0. Node.js v14.21.2. linux 5.4.0-1100-azure x64.
Outcome: success User: codespace WorkspaceFolder: /workspaces/workspace
devcontainer process exited with exit code 0
Configuring codespace...
Finished configuring codespace.
Configuration starting...
Cloning...
$ df /var/lib/docker
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/loop0      32847680 20902780  10250804  68% /var/lib/docker
df process exited with exit code 0
$ git -C "/var/lib/docker/codespacemount/workspace" clone --branch main --depth 1 https://github.com/pamelafox/simple-flask-server-example "/var/lib/docker/codespacemount/workspace/simple-flask-server-example"
Cloning into '/var/lib/docker/codespacemount/workspace/simple-flask-server-example'...
git process exited with exit code 0
$ git -C "/var/lib/docker/codespacemount/workspace/simple-flask-server-example" config --local remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
git process exited with exit code 0
Creating container...
$ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/simple-flask-server-example --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --skip-non-blocking-commands --skip-post-create --config "/var/lib/docker/codespacemount/workspace/simple-flask-server-example/.devcontainer/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache
[244 ms] @devcontainers/cli 0.28.0. Node.js v14.21.2. linux 5.4.0-1100-azure x64.
{"outcome":"error","message":"Failed to process feature ghcr.io/devcontainers/features/python:1","description":"An error occurred setting up the container."}
Error: Failed to process feature ghcr.io/devcontainers/features/python:1
    at Cne (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1827:3091)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async nm (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1827:2243)
    at async Lf (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1829:1773)
    at async pie (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1915:2559)
    at async AF (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1915:1963)
    at async P7 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1915:901)
    at async Fie (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1921:2093)
    at async $f (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1921:3239)
    at async eoe (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2045:17247)
devcontainer process exited with exit code 1
Failed to create container.
Error: Failed to process feature ghcr.io/devcontainers/features/python:1
Error Code: 1302
Container creation failed.
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for the report. Looks like GitHub packages are  🔴 and has an ongoing incident. Features depend on them as they are stored as GitHub packages on ghcr.io. Hence, devcontainers are impacted as well.

https://www.githubstatus.com/
https://www.githubstatus.com/incidents/zf2tk6x40gmh

**Comment by samruddhikhandale** [comment]
Packages are 🟢 
Closing as dev container is built successfully!
