### ISSUE TITLE
docker-in-docker feature issues on Mac M1 Pro

### ISSUE THREAD

**Issue by bogdanmelinte** [devcontainers/features#446]
Hello guys,

Since yesterday, I started encountering issues building devcontainers that include the docker-in-docker feature.

I'm getting the following error when trying to build the container:

> [2023-02-08T09:36:30.763Z] error: failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = error getting credentials - err: exit status 255, out: ``
[2023-02-08T09:36:30.765Z] Stop (917 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.29.0-1675848983162 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-ssp-external-042dcff4e38ebc295fd11392f0cee097-features -f /tmp/devcontainercli-root/container-features/0.29.0-1675848983162/Dockerfile.extended /tmp/devcontainercli-root/empty-folder
[2023-02-08T09:36:30.735Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.29.0-1675848983162 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:bullseye --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-ssp-external-042dcff4e38ebc295fd11392f0cee097-features -f /tmp/devcontainercli-root/container-features/0.29.0-1675848983162/Dockerfile.extended /tmp/devcontainercli-root/empty-folder
[2023-02-08T09:36:30.735Z]     at fie (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:1355)
[2023-02-08T09:36:30.735Z]     at P7 (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:1291)
[2023-02-08T09:36:30.735Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-02-08T09:36:30.735Z]     at async Fie (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[2023-02-08T09:36:30.735Z]     at async Vf (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[2023-02-08T09:36:30.735Z]     at async eoe (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[2023-02-08T09:36:30.735Z]     at async Qse (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17065)

**Comment by samruddhikhandale** [comment]
Hi 👋 

I tried to build a dev container with simple configuration on Mac M1 Pro, it worked for me. @bogdanmelinte can you add your dev config here which may help us understand the issue?

devcontainer.json
```jsonc
{
	"name": "Docker in Docker",
	"image": "mcr.microsoft.com/devcontainers/base:bullseye",
	"features": {
		"ghcr.io/devcontainers/features/docker-in-docker:2": {}
	}
}
```

Also, I'd recommend using the simple config above and see if that works for you. This will help us narrow down whether the issue exists with the Feature or with dev config.

**Comment by bogdanmelinte** [comment]
Hi 👋

Solved it after a few hours debugging everything.

Apparently the issue was that I was missing docker-credential-helper on my Mac and this was leading to weird auth issues with the registry.

All good now.

Thank you !
