### ISSUE TITLE
Java feature fails to install, resulting in codespace creation failed

### ISSUE THREAD

**Issue by vedantmgoyal2009** [devcontainers/features#454]
Logs (only needed has been attached):

```
2023-02-15 13:38:42.844Z: #21 0.630 ===========================================================================
#21 0.630 Feature       : Java (via SDKMAN!)
#21 0.630 Description   : Installs Java, SDKMAN! (if not installed), and needed dependencies.
#21 0.630 Id            : ghcr.io/devcontainers/features/java
#21 0.630 Version       : 1.2.1
#21 0.630 Documentation : https://github.com/devcontainers/features/tree/main/src/java
#21 0.630 Options       :
#21 0.630     VERSION="latest"
#21 0.630     JDKDISTRO="ms"
#21 0.630     INSTALLGRADLE="true"
#21 0.630     GRADLEVERSION="latest"
#21 0.630     INSTALLMAVEN="false"
#21 0.630     MAVENVERSION="latest"
#21 0.630     INSTALLANT="false"
#21 0.630     ANTVERSION="latest"
#21 0.630 ===========================================================================
2023-02-15 13:38:43.295Z: #21 1.102 
#21 1.102                                 -+syyyyyyys:
2023-02-15 13:38:43.298Z: #21 1.102                             `/yho:`       -yd.
#21 1.102                          `/yh/`             +m.
#21 1.102                        .oho.                 hy                          .`
#21 1.102                      .sh/`                   :N`                `-/o`  `+dyyo:.
#21 1.102                    .yh:`                     `M-          `-/osysoym  :hs` `-+sys:      hhyssssssssy+
#21 1.103                  .sh:`                       `N:          ms/-``  yy.yh-      -hy.    `.N-````````+N.
#21 1.103                `od/`                         `N-       -/oM-      ddd+`     `sd:     hNNm        -N:
#21 1.103               :do`                           .M.       dMMM-     `ms.      /d+`     `NMMs       `do
#21 1.103             .yy-                             :N`    ```mMMM.      -      -hy.       /MMM:       yh
#21 1.103           `+d+`           `:/oo/`       `-/osyh/ossssssdNMM`           .sh:         yMMN`      /m.
#21 1.103          -dh-           :ymNMMMMy  `-/shmNm-`:N/-.``   `.sN            /N-         `NMMy      .m/
#21 1.104        `oNs`          -hysosmMMMMydmNmds+-.:ohm           :             sd`        :MMM/      yy
2023-02-15 13:38:43.299Z: #21 1.104       .hN+           /d:    -MMMmhs/-.`   .MMMh   .ss+-                 `yy`       sMMN`     :N.
#21 1.104      :mN/           `N/     `o/-`         :MMMo   +MMMN-         .`      `ds       mMMh      do
#21 1.104     /NN/            `N+....--:/+oooosooo+:sMMM:   hMMMM:        `my       .m+     -MMM+     :N.
#21 1.104    /NMo              -+ooooo+/:-....`...:+hNMN.  `NMMMd`        .MM/       -m:    oMMN.     hs
#21 1.105   -NMd`                                    :mm   -MMMm- .s/     -MMm.       /m-   mMMd     -N.
#21 1.105  `mMM/                                      .-   /MMh. -dMo     -MMMy        od. .MMMs..---yh
#21 1.105  +MMM.                                           sNo`.sNMM+     :MMMM/        sh`+MMMNmNm+++-
#21 1.105  mMMM-                                           /--ohmMMM+     :MMMMm.       `hyymmmdddo
#21 1.105  MMMMh.                  ````                  `-+yy/`yMMM/     :MMMMMy       -sm:.``..-:-.`
#21 1.105  dMMMMmo-.``````..-:/osyhddddho.           `+shdh+.   hMMM:     :MmMMMM/   ./yy/` `:sys+/+sh/
#21 1.106  .dMMMMMMmdddddmmNMMMNNNNNMMMMMs           sNdo-      dMMM-  `-/yd/MMMMm-:sy+.   :hs-      /N`
#21 1.106   `/ymNNNNNNNmmdys+/::----/dMMm:          +m-         mMMM+ohmo/.` sMMMMdo-    .om:       `sh
#21 1.106      `.-----+/.`       `.-+hh/`         `od.          NMMNmds/     `mmy:`     +mMy      `:yy.
#21 1.106            /moyso+//+ossso:.           .yy`          `dy+:`         ..       :MMMN+---/oys:
#21 1.106          /+m:  `.-:::-`               /d+                                    +MMMMMMMNh:`
#21 1.107         +MN/                        -yh.                                     `+hddhy+.
#21 1.107        /MM+                       .sh:
#21 1.107       :NMo                      -sh/
#21 1.107      -NMs                    `/yy:
#21 1.107     .NMy                  `:sh+.
#21 1.107    `mMm`               ./yds-
#21 1.107   `dMMMmyo:-.````.-:oymNy:`
#21 1.107   +NMMMMMMMMMMMMMMMMms:`
#21 1.107     -+shmNMMMNmdy+:`
#21 1.108 
#21 1.108 
#21 1.108                                                                  Now attempting installation...
#21 1.108 
#21 1.108 
#21 1.108 Looking for a previous installation of SDKMAN...
#21 1.109 Looking for unzip...
#21 1.109 Looking for zip...
#21 1.110 Looking for curl...
#21 1.111 Looking for sed...
#21 1.112 Installing SDKMAN scripts...
#21 1.112 Create distribution directories...
#21 1.117 Getting available candidates...
2023-02-15 13:38:43.431Z: #21 1.231 Prime the config file...
2023-02-15 13:38:43.434Z: #21 1.245 Installing script cli archive...
#21 1.245 * Downloading...
#21 1.340 curl: (22) The requested URL returned error: 503
#21 1.340 
2023-02-15 13:38:43.560Z: #21 1.342 'curl --fail --location --progress-bar "$download_url" > "$sdkman_zip_file"': command failed with exit code 22.
#21 1.343 ERROR: Feature "Java (via SDKMAN!)" (ghcr.io/devcontainers/features/java) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/java for help troubleshooting this error.
2023-02-15 13:38:43.562Z: #21 ERROR: executor failed running [/bin/sh -c cd /tmp/build-features/java_6 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 22
2023-02-15 13:38:43.603Z: ------
 > [dev_containers_target_stage  9/13] RUN cd /tmp/build-features/java_6 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#21 1.112 Installing SDKMAN scripts...
2023-02-15 13:38:43.605Z: #21 1.112 Create distribution directories...
#21 1.117 Getting available candidates...
#21 1.231 Prime the config file...
#21 1.245 Installing script cli archive...
#21 1.245 * Downloading...
#21 1.340 curl: (22) The requested URL returned error: 503
#21 1.340 
#21 1.342 'curl --fail --location --progress-bar "$download_url" > "$sdkman_zip_file"': command failed with exit code 22.
#21 1.343 ERROR: Feature "Java (via SDKMAN!)" (ghcr.io/devcontainers/features/java) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/java for help troubleshooting this error.
------
2023-02-15 13:38:43.606Z: ERROR: failed to solve: executor failed running [/bin/sh -c cd /tmp/build-features/java_6 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 222023-02-15 13:38:43.608Z: 
2023-02-15 13:38:43.614Z: Stop: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.28.0-1676467932737 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:jammy --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-vedantmgoyal2009-ecbf86432b2feb408cef6404eab61220-features -f /tmp/devcontainercli-root/container-features/0.28.0-1676467932737/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2023-02-15 13:38:43.618Z: Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.28.0-1676467932737 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:jammy --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-vedantmgoyal2009-ecbf86432b2feb408cef6404eab61220-features -f /tmp/devcontainercli-root/container-features/0.28.0-1676467932737/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2023-02-15 13:38:43.619Z:     at fie (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1915:1355)
2023-02-15 13:38:43.620Z:     at P7 (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1915:1291)
2023-02-15 13:38:43.624Z:     at runMicrotasks (<anonymous>)
2023-02-15 13:38:43.628Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2023-02-15 13:38:43.633Z:     at async Fie (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1921:2093)
2023-02-15 13:38:43.634Z:     at async $f (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:1921:3239)
2023-02-15 13:38:43.635Z:     at async eoe (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2045:17247)
2023-02-15 13:38:43.636Z:     at async Qse (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:2045:16993)
2023-02-15 13:38:43.638Z: {"outcome":"error","message":"Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.28.0-1676467932737 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:jammy --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-vedantmgoyal2009-ecbf86432b2feb408cef6404eab61220-features -f /tmp/devcontainercli-root/container-features/0.28.0-1676467932737/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder","description":"An error occurred setting up the container."}
2023-02-15 13:38:43.639Z: devcontainer process exited with exit code 1

====================================== ERROR ====================================
2023-02-15 13:38:43.640Z: Failed to create container.
=================================================================================
2023-02-15 13:38:43.665Z: Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.28.0-1676467932737 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:jammy --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-vedantmgoyal2009-ecbf86432b2feb408cef6404eab61220-features -f /tmp/devcontainercli-root/container-features/0.28.0-1676467932737/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
2023-02-15 13:38:43.666Z: Error Code: 1302

====================================== ERROR ====================================
2023-02-15 13:38:43.685Z: Container creation failed.
=================================================================================
2023-02-15 13:38:43.715Z: 

===================================== WARNING ===================================
2023-02-15 13:38:43.719Z: Creating recovery container.
=================================================================================
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

> curl: (22) The requested URL returned error: 503

Even I was seeing similar timeouts from the `sdkman-cli` which seemed like an upstream (temporary) issue. Running sdkman locally (without using this Feature) was failing with same errors. However, things started working approx 8 hours ago. Can you retry and see if things are working for you now?

Tested the `java` Feature which is currectly installing and running tests - https://github.com/devcontainers/features/actions/runs/4189570799/jobs/7262047433#step:4:1827

**Comment by samruddhikhandale** [comment]
Feel free to reopen the issue if the problem resurfaces, thanks!

**Comment by trevor-brandt** [comment]
I'm seeing these with increased frequency lately. Same issue--503 on the download. @samruddhikhandale, not sure if you're still on a maintaining team, but it's been a little disruptive for our CI build process. Any thoughts on how we can mitigate this without having to hook up retries to our `devcontainer build` call? (Feels like a heavy-handed solution.)
