### ISSUE TITLE
Docker-in-Docker Feature "Failed to parse manifest" Error

### ISSUE THREAD

**Issue by poita66** [devcontainers/features#466]
The docker-in-docker:2 feature is failing to load, preventing my devcontainer from building

I think this is to do with the manifest URL requiring authorization (the URL from the logs below: https://ghcr.io/v2/devcontainers/features/docker-in-docker/manifests/2), as if I visit that URL, I get a HTTP 401

Versions: Dev Containers 0.275.1 in VS Code 1.75.1 (441438abd1ac652551dbe4d408dfcec8a499b8bf).

Relevant part of trace log:
```
[2023-03-01T06:36:27.388Z] --- Processing User Features ----
[2023-03-01T06:36:27.388Z] configPath: /workspaces/healthbydesign-kentico/.devcontainer/devcontainer.json
[2023-03-01T06:36:27.389Z] * Processing feature: ghcr.io/devcontainers/features/docker-in-docker:2
[2023-03-01T06:36:27.389Z] > input: ghcr.io/devcontainers/features/docker-in-docker:2
[2023-03-01T06:36:27.389Z] >
[2023-03-01T06:36:27.389Z] > resource: ghcr.io/devcontainers/features/docker-in-docker
[2023-03-01T06:36:27.389Z] > id: docker-in-docker
[2023-03-01T06:36:27.389Z] > version: 2
[2023-03-01T06:36:27.389Z] > owner: devcontainers
[2023-03-01T06:36:27.389Z] > namespace: devcontainers/features
[2023-03-01T06:36:27.389Z] > registry: ghcr.io
[2023-03-01T06:36:27.389Z] > path: devcontainers/features/docker-in-docker
[2023-03-01T06:36:27.389Z] manifest url: https://ghcr.io/v2/devcontainers/features/docker-in-docker/manifests/2
[2023-03-01T06:36:32.419Z] Failed to parse manifest: 
[2023-03-01T06:36:32.419Z] (!) WARNING: Falling back to deprecated GitHub Release syntax. See https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#referencing-a-feature for updated specification.
[2023-03-01T06:36:32.419Z] Github feature.
[2023-03-01T06:36:32.420Z] Could not resolve Feature 'ghcr.io/devcontainers/features/docker-in-docker:2'.  Ensure the Feature is published and accessible from your current environment.
[2023-03-01T06:36:32.424Z] Error: Failed to process feature ghcr.io/devcontainers/features/docker-in-docker:2
[2023-03-01T06:36:32.424Z]     at Cne (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1827:3109)
[2023-03-01T06:36:32.425Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-03-01T06:36:32.426Z]     at async nm (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1827:2243)
[2023-03-01T06:36:32.426Z]     at async Uf (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1829:1773)
[2023-03-01T06:36:32.427Z]     at async pie (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:2568)
[2023-03-01T06:36:32.428Z]     at async vF (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:1972)
[2023-03-01T06:36:32.428Z]     at async P7 (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1915:901)
[2023-03-01T06:36:32.429Z]     at async Fie (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:2093)
[2023-03-01T06:36:32.429Z]     at async Vf (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:1921:3241)
[2023-03-01T06:36:32.430Z]     at async eoe (/root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js:2045:17324)
[2023-03-01T06:36:32.438Z] Stop (5596 ms): Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.275.1/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-1ed5cbc2-8d12-4729-af93-7e669e3d83fb1677652582029 --workspace-folder /workspaces/healthbydesign-kentico --workspace-mount-consistency cached --id-label vsch.local.repository=git@bitbucket.org:curiousitteam/healthbydesign-kentico.git --id-label vsch.local.repository.volume=vsc-remote-containers-hbd --id-label vsch.local.repository.folder=healthbydesign-kentico --id-label devcontainer.config_file=/workspaces/healthbydesign-kentico/.devcontainer/devcontainer.json --log-level trace --log-format json --config /workspaces/healthbydesign-kentico/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-3b5b5f59-f4a8-4abc-b427-26bc278273b2.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=volume,source=vsc-remote-containers-hbd,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=/run/user/1000/wayland-0,target=/tmp/vscode-wayland-cb701d2e9add07db74ee793f0ba9358c55ebf2da.sock --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root true
[2023-03-01T06:36:32.439Z] Exit code 1
```

**Comment by poita66** [comment]
This turned out to be a connectivity issue with Docker. Restarting Docker and then reopening and rebuilding the devcontainer has fixed the issue. This happened after adding `--net=host` and removing it.
