### ISSUE TITLE
Could not resolve Feature 'ghcr.io/devcontainers/features/docker-in-docker:2'

### ISSUE THREAD

**Issue by pblack** [devcontainers/features#492]
this [page](https://github.com/devcontainers/features/tree/main/src/docker-in-docker) and this [page](https://containers.dev/features) indicates version `2` should be used but when I have that in my `devcontainer.json` file and try to `open in a container` I receive the following error:
```
451278 ms] Could not resolve Feature 'ghcr.io/devcontainers/features/docker-in-docker:2'.  Ensure the Feature is published and accessible from your current environment.
[451278 ms] Error: Failed to process feature ghcr.io/devcontainers/features/docker-in-docker:2
    at bne (/Users/pblackknight/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1850:3109)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async am (/Users/pblackknight/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:1850:2243)
    at async yoe (/Users/pblackknight/.vscode/extensions/ms-vscode-remote.remote-containers-0.282.0/dist/spec-node/devContainersSpecCLI.js:2069:40854)
```

rolling back to version `1` works but its not clear if this is a documentation error or what. I'm on in Intel Mac on OSX 13.0.1 with dev containers feature v0.282.0, VSCode 1.76.1, docker desktop 4.15.0 (93002)/Engine 20.10.21.

Interestingly, the v `2` works in codespace.

**Comment by samruddhikhandale** [comment]
Hi 👋 

Interesting, both versions of `docker-in-docker` Feature works for me.

From https://github.com/devcontainers/features/issues/466. 
> Restarting Docker and then reopening and rebuilding the devcontainer has fixed the issue.

Can you try and see if it helps?

**Comment by pblack** [comment]
Weird...seems to be working today.
