### ISSUE TITLE
kubectl-helm-minikube feature fails to install in my codespaces

### ISSUE THREAD

**Issue by oliverlabs** [devcontainers/features#523]
The [kubectl-helm-minikube](https://github.com/devcontainers/features/tree/main/src/kubectl-helm-minikube) feature fails in my container. It seems to be a yarn gpg signature error.

Here's how I call it in my `devcontainer.json`:

```shell
"ghcr.io/devcontainers/features/kubectl-helm-minikube:latest": {
			"version": "latest"
		}
```

I am using the following docker image as a base: 
`FROM mcr.microsoft.com/devcontainers/dotnet:0-3.1`

It seems to be running on Ubuntu:

```shell
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

Here's an output of my container build:

```shell
#26 [dev_containers_target_stage 12/25] COPY --chown=root:root --from=dev_containers_feature_content_source /tmp/build-features/kubectl-helm-minikube_6 /tmp/dev-container-features/kubectl-helm-minikube_6
#26 DONE 1.1s

#27 [dev_containers_target_stage 13/25] RUN chmod -R 0755 /tmp/dev-container-features/kubectl-helm-minikube_6 && cd /tmp/dev-container-features/kubectl-helm-minikube_6 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh
#27 1.377 ===========================================================================
#27 1.377 Feature       : Kubectl, Helm, and Minikube
#27 1.377 Description   : Installs latest version of kubectl, Helm, and optionally minikube. Auto-detects latest versions and installs needed dependencies.
#27 1.377 Id            : ghcr.io/devcontainers/features/kubectl-helm-minikube
#27 1.377 Version       : 1.1.4
#27 1.377 Documentation : https://github.com/devcontainers/features/tree/main/src/kubectl-helm-minikube
#27 1.377 Options       :
#27 1.377     VERSION="latest"
#27 1.377     HELM="latest"
#27 1.377     MINIKUBE="latest"
#27 1.377 ===========================================================================
#27 1.397 find: '/var/lib/apt/lists/*': No such file or directory
#27 1.398 Running apt-get update...
#27 1.468 Get:1 https://packages.microsoft.com/repos/azure-cli focal InRelease [3575 B]
#27 1.483 Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
#27 1.541 Get:3 https://packages.microsoft.com/repos/azure-cli focal/main all Packages [4106 B]
#27 1.550 Get:4 https://packages.microsoft.com/repos/azure-cli focal/main amd64 Packages [564 B]
#27 1.610 Err:2 https://dl.yarnpkg.com/debian stable InRelease
#27 1.610   The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
#27 1.995 Get:5 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]#27 2.075 Get:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
#27 2.095 Get:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
#27 2.202 Get:8 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
#27 2.230 Get:9 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
#27 2.244 Get:10 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
#27 2.389 Get:11 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
#27 2.411 Get:12 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [31.2 kB]
#27 2.414 Get:13 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2277 kB]
#27 2.440 Get:14 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3111 kB]
#27 2.468 Get:15 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1329 kB]
#27 2.546 Get:16 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
#27 2.587 Get:17 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
#27 6.240 Get:18 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
#27 6.751 Get:19 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2629 kB]
#27 13.29 Get:20 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1033 kB]
#27 14.53 Get:21 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [28.5 kB]
#27 14.55 Get:22 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [2139 kB]#27 20.36 Reading package lists...
#27 21.39 W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
#27 21.39 E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
#27 21.39 ERROR: Feature "Kubectl, Helm, and Minikube" (ghcr.io/devcontainers/features/kubectl-helm-minikube) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/kubectl-helm-minikube for help troubleshooting this error.
#27 ERROR: executor failed running [/bin/sh -c chmod -R 0755 /tmp/dev-container-features/kubectl-helm-minikube_6 && cd /tmp/dev-container-features/kubectl-helm-minikube_6 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 100
------
 > [dev_containers_target_stage 13/25] RUN chmod -R 0755 /tmp/dev-container-features/kubectl-helm-minikube_6 && cd /tmp/dev-container-features/kubectl-helm-minikube_6 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh:
#27 2.587 Get:17 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
#27 6.240 Get:18 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
#27 6.751 Get:19 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2629 kB]
#27 13.29 Get:20 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [1033 kB]
#27 14.53 Get:21 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [28.5 kB]
#27 14.55 Get:22 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [2139 kB]

#27 21.39 W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
#27 21.39 E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
#27 21.39 ERROR: Feature "Kubectl, Helm, and Minikube" (ghcr.io/devcontainers/features/kubectl-helm-minikube) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/kubectl-helm-minikube for help troubleshooting this error.
------
error: failed to solve: executor failed running [/bin/sh -c chmod -R 0755 /tmp/dev-container-features/kubectl-helm-minikube_6 && cd /tmp/dev-container-features/kubectl-helm-minikube_6 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh]: exit code: 100Stop: Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.37.0-1681911685[465](https://github.com/oliverlabs/azdevcont/actions/runs/4744023783/jobs/8424343274#step:4:466)/Dockerfile-with-features -t vsc-azdevcont-163ecb3852c7898f1345cb05d441b576057f682[480](https://github.com/oliverlabs/azdevcont/actions/runs/4744023783/jobs/8424343274#step:4:481)f9d767efb2ddbff3e0c26d --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/azdevcont/.devcontainer
{"outcome":"error","message":"Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.37.0-1681911685465/Dockerfile-with-features -t vsc-azdevcont-163ecb3852c7898f1345cb05d441b576057f682480f9d767efb2ddbff3e0c26d --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/azdevcont/.devcontainer","description":"An error occurred building the image."}
Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.37.0-1681911685465/Dockerfile-with-features -t vsc-azdevcont-163ecb3852c7898f1345cb05d441b576057f682480f9d767efb2ddbff3e0c26d --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/azdevcont/.devcontainer
    at _se (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1917:1698)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async CD (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1916:3889)
    at async K7 (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1916:2808)
    at async Hse (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1931:2626)
    at async Ch (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:1931:3741)
    at async cae (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2059:17376)
    at async uae (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2059:17117)
devcontainer process exited with exit code 1
Failed to create container.
Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-root/container-features/0.37.0-1681911685465/Dockerfile-with-features -t vsc-azdevcont-163ecb3852c7898f1345cb05d441b576057f682480f9d767efb2ddbff3e0c26d --target dev_containers_target_stage --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /var/lib/docker/codespacemount/workspace/azdevcont/.devcontainer
Error Code: 1302
Container creation failed.
Jobs failed, exiting the agent. Error Code: 1302
Error: Process completed with exit code 1.
```

**Comment by oliverlabs** [comment]
@samruddhikhandale any help would be appreciated.

**Comment by samruddhikhandale** [comment]
Hi 👋 

The problem in this case is with the `mcr.microsoft.com/devcontainers/dotnet:0-3.1` image, this image was deprecated in Dec 2022 and did not get an update since. 

From https://github.com/devcontainers/images/issues/370, the yarn GPG key was expired, which caused apt issues for all the past images. 

All the currently supported images were patched, @oliverlabs would it be possible to use the [currently supported images instead](https://github.com/devcontainers/images/issues/90)? Else, you should be able to unblock with the workaround mentioned in https://github.com/devcontainers/images/issues/370#issuecomment-1402753345

**Comment by oliverlabs** [comment]
Thanks so much for providing this info, @samruddhikhandale. Yes, I'll just change the base image to Ubuntu:jammy. Good shout. I am very impressed with the level of support :)
