### ISSUE TITLE
docker-in-docker feature doesn't work with specific version

### ISSUE THREAD

**Issue by kse3hi** [devcontainers/features#525]
Input:
1. Documentation: https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/docker-in-docker.md
2. Release version of docker-in-docker: https://github.com/devcontainers/features/pkgs/container/features%2Fdocker-in-docker

docker-in-docker latest **works** fine
```xml
	"features": {
		"docker-in-docker": {
			"version": "latest"
		}
	}
```

docker-in-docker 2.1.0 **DOESN'T** work and fail - devcontainer building process fail
```xml
	"features": {
		"docker-in-docker": {
			"version": "2.1.0"
		}
	}
```

_Error message:_
```
#0 26.18 ERROR: Feature "Docker (Docker-in-Docker)" (docker-in-docker) failed to
 install! Look at the documentation at https://github.com/devcontainers/features
/tree/main/src/docker-in-docker for help troubleshooting this error.
------
ERROR: failed to solve: executor failed running [/bin/sh -c cp -ar /tmp/build-fe
atures-src/docker-in-docker_1 /tmp/dev-container-features  && chmod -R 0755 /tmp
/dev-container-features/docker-in-docker_1  && cd /tmp/dev-container-features/do
cker-in-docker_1  && chmod +x ./devcontainer-features-install.sh  && ./devcontai
ner-features-install.sh  && rm -rf /tmp/dev-container-features/docker-in-docker_
1]: exit code: 1
[2023-04-20T08:39:41.256Z] Stop (210267 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\user_id\AppData\Local\Temp\devcontainercli\container-features\0.35.0-1681979768791\Dockerfile-with-features -t vsc-license-check-25c4dc36aafe626997ff0ba7fae1896116eca711434df63c3c8df805647592e9 --target dev_containers_target_stage --no-cache --pull --build-arg VARIANT=3.10 --build-arg NODE_VERSION=lts/* --build-context dev_containers_feature_content_source=C:\Users\user_id\AppData\Local\Temp\devcontainercli\container-features\0.35.0-1681979768791 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp c:\Users\user_id\Developer\swdc\license-check
[2023-04-20T08:39:41.262Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\Users\user_id\AppData\Local\Temp\devcontainercli\container-features\0.35.0-1681979768791\Dockerfile-with-features -t vsc-license-check-25c4dc36aafe626997ff0ba7fae1896116eca711434df63c3c8df805647592e9 --target dev_containers_target_stage --no-cache --pull --build-arg VARIANT=3.10 --build-arg NODE_VERSION=lts/* --build-context dev_containers_feature_content_source=C:\Users\user_id\AppData\Local\Temp\devcontainercli\container-features\0.35.0-1681979768791 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp c:\Users\user_id\Developer\swdc\license-check
[2023-04-20T08:39:41.263Z]     at Sse (c:\Users\user_id\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.1\dist\spec-node\devContainersSpecCLI.js:1917:1698)
[2023-04-20T08:39:41.263Z]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-04-20T08:39:41.264Z]     at async AD (c:\Users\user_id\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.1\dist\spec-node\devContainersSpecCLI.js:1916:3889)
[2023-04-20T08:39:41.264Z]     at async J7 (c:\Users\user_id\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.1\dist\spec-node\devContainersSpecCLI.js:1916:2808)
[2023-04-20T08:39:41.265Z]     at async $se (c:\Users\user_id\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.1\dist\spec-node\devContainersSpecCLI.js:1931:2626)
[2023-04-20T08:39:41.266Z]     at async Ah (c:\Users\user_id\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.1\dist\spec-node\devContainersSpecCLI.js:1931:3741)
[2023-04-20T08:39:41.266Z]     at async aae (c:\Users\user_id\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.1\dist\spec-node\devContainersSpecCLI.js:2059:17376)
[2023-04-20T08:39:41.266Z]     at async oae (c:\Users\user_id\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.1\dist\spec-node\devContainersSpecCLI.js:2059:17117)
[2023-04-20T08:39:41.293Z] Stop (222983 ms): Run: C:\Users\user_id\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\user_id\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.1\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\user_id\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-a63cc227-c3ff-4b53-afb8-5ff74ed56e2a1681979732900 --workspace-folder c:\Users\user_id\Developer\swdc\license-check --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\user_id\Developer\swdc\license-check --id-label devcontainer.config_file=c:\Users\user_id\Developer\swdc\license-check\.devcontainer\devcontainer.json --log-level trace --log-format json --config c:\Users\user_id\Developer\swdc\license-check\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-04-20T08:39:41.294Z] Exit code 1
[2023-04-20T08:39:41.304Z] Command failed: C:\Users\user_id\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\user_id\.vscode\extensions\ms-vscode-remote.remote-containers-0.288.1\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\user_id\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-a63cc227-c3ff-4b53-afb8-5ff74ed56e2a1681979732900 --workspace-folder c:\Users\user_id\Developer\swdc\license-check --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\user_id\Developer\swdc\license-check --id-label devcontainer.config_file=c:\Users\user_id\Developer\swdc\license-check\.devcontainer\devcontainer.json --log-level trace --log-format json --config c:\Users\user_id\Developer\swdc\license-check\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-04-20T08:39:41.305Z] Exit code 1

```

**Comment by samruddhikhandale** [comment]
Hi 👋 

> Documentation: https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/docker-in-docker.md

Looks like there is a confusion in adding the dev container Feature to the `devcontainer.json`

The [documentation](https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/docker-in-docker.md) that you've linked is an older approach of adding Features. We've migrated the Features to a new repo and they are now published to an OCI registry with newer syntax.

> docker-in-docker 2.1.0 DOESN'T work and fail - devcontainer building process fail

I am guessing you want to pin the `2.1.0` version of the Feature and not the version of docker/moby? You can do it as follows 👇 

```jsonc
"features": {
  "ghcr.io/devcontainers/features/docker-in-docker:2.1.0": {}
}
```

> "version": "2.1.0"

ℹ️  As mentioned in https://github.com/devcontainers/features/tree/main/src/docker-in-docker#options, the `version` parameter is defined as `Select or enter a Docker/Moby Engine version. (Availability can vary by OS version.)` ; doesn't look like v2.1.0 is any longer supported. Probably, there was a confusion with Feature version vs Docker version in this case.

Let us know if this helps, thanks!

**Comment by kse3hi** [comment]
Hello @samruddhikhandale ,

your suggestion works fine. I think you need to remove/edit documentation in https://github.com/microsoft/vscode-dev-containers/blob/main/script-library/docs/docker-in-docker.md to stop confusing people :)
