### ISSUE TITLE
Node Feature fails when zsh is configured as default shell on Ubuntu dev container

### ISSUE THREAD

**Issue by oliverlabs** [devcontainers/features#569]
I am using a base Ubuntu (latest) image: `"image": "mcr.microsoft.com/devcontainers/base:ubuntu"`.

I am specifying the node as a feature like so:

```
"features": {
    "ghcr.io/devcontainers/features/node:1": {}
}
```

This fails my devcontainer build:

Here's an error message:

```
#21 [dev_containers_target_stage  9/14] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=node_6,target=/tmp/build-features-src/node_6     cp -ar /tmp/build-features-src/node_6 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/node_6  && cd /tmp/dev-container-features/node_6  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/node_6
#21 0.677 ===========================================================================#21 0.677 Feature       : Node.js (via nvm), yarn and pnpm#21 0.677 Description   : Installs Node.js, nvm, yarn, pnpm, and needed dependencies.#21 0.677 Id            : ghcr.io/devcontainers/features/node#21 0.677 Version       : 1.2.0#21 0.677 Documentation : https://github.com/devcontainers/features/tree/main/src/node#21 0.677 Options       :
#21 0.677     VERSION="lts"
#21 0.677     NODEGYPDEPENDENCIES="true"
#21 0.677     NVMINSTALLPATH="/usr/local/share/nvm"
#21 0.677     NVMVERSION="0.39.2"
#21 0.677 ===========================================================================
#21 0.882 Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
#21 0.886 Get:2 https://packages.microsoft.com/repos/azure-cli jammy InRelease [[357](https://github.com/oliverlabs/azdevcont/actions/runs/5212210292/jobs/9405513410#step:4:358)5 B]
#21 0.893 Get:3 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
#21 0.936 Get:4 https://packages.microsoft.com/repos/azure-cli jammy/main amd64 Packages [786 B]
#21 0.948 Get:5 https://packages.microsoft.com/repos/azure-cli jammy/main all Packages [1096 B]
#21 0.995 Get:6 https://dl.yarnpkg.com/debian stable/main all Packages [11.1 kB]
#21 1.007 Get:7 https://dl.yarnpkg.com/debian stable/main amd64 Packages [11.1 kB]
#21 1.042 Get:8 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
#21 1.072 Get:9 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [449 kB]#21 1.117 Get:10 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [36.3 kB]
#21 1.118 Get:11 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [928 kB]
#21 1.137 Get:12 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [569 kB]
#21 1.491 Get:13 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
#21 1.597 Get:14 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
#21 1.702 Get:15 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
#21 1.951 Get:16 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
#21 1.959 Get:17 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
#21 1.973 Get:18 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
#21 2.471 Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [457 kB]#21 2.476 Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [857 kB]#21 2.508 Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [42.2 kB]
#21 2.510 Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1176 kB]
#21 2.710 Get:23 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [49.4 kB]
#21 2.959 Get:24 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [27.0 kB]
#21 3.449 Fetched 24.9 MB in 3s (9590 kB/s)
#21 3.449 Reading package lists...#21 4.234 Reading package lists...#21 4.955 Building dependency tree...
#21 5.119 Reading state information...
#21 5.259 Recommended packages:
#21 5.259   nodejs
#21 5.279 The following NEW packages will be installed:
#21 5.279   yarn
#21 5.363 0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
#21 5.363 Need to get 893 kB of archives.
#21 5.363 After this operation, 5415 kB of additional disk space will be used.
#21 5.363 Get:1 https://dl.yarnpkg.com/debian stable/main amd64 yarn all 1.22.19-1 [893 kB]
#21 6.411 Fetched 893 kB in 0s (9672 kB/s)
#21 6.479 Selecting previously unselected package yarn.

#21 6.479 (Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 59214 files and directories currently installed.)

#21 6.508 Preparing to unpack .../yarn_1.22.19-1_all.deb ...

#21 6.555 Unpacking yarn (1.22.19-1) ...

#21 6.953 Setting up yarn (1.22.19-1) ...

#21 7.574 => Downloading nvm from git to '/usr/local/share/nvm'
#21 7.574 > Cloning into '/usr/local/share/nvm'...
#21 8.492 * (HEAD detached at FETCH_HEAD)
#21 8.492   master
#21 8.495 => Compressing and cleaning up git repository
#21 8.499 
#21 8.502 => Profile not found. Tried  (as defined in $PROFILE), ~/.bashrc, ~/.bash_profile, ~/.zprofile, ~/.zshrc, and ~/.profile.
#21 8.502 => Create one of them and run this script again
#21 8.502    OR
#21 8.502 => Append the following lines to the correct file yourself:
#21 8.502 
#21 8.502 export NVM_DIR="/usr/local/share/nvm"
#21 8.502 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#21 8.503 
#21 8.530 => Installing Node.js version lts/*
#21 8.782 Downloading and installing node v18.16.0...
#21 8.941 Downloading https://nodejs.org/dist/v18.16.0/node-v18.16.0-linux-x64.tar.xz...
#21 9.077 
                                                                           0.2%
#########################################                                 57.2%
######################################################################## 100.0%
#21 9.258 Computing checksum with sha256sum#21 9.390 Checksums matched!#21 12.10 Now using node v18.16.0 (npm v9.5.1)
#21 12.24 Creating default alias: default -> lts/* (-> v18.16.0 *)
#21 12.33 => Node.js version lts/* has been successfully installed
#21 12.33 => Close and reopen your terminal to start using nvm or run the following to use it now:
#21 12.33 
#21 12.33 export NVM_DIR="/usr/local/share/nvm"
#21 12.33 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#21 12.61 zsh:8: no matches found: lts/*
#21 12.61 ERROR: Feature "Node.js (via nvm), yarn and pnpm" (ghcr.io/devcontainers/features/node) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/node for help troubleshooting this error.
#21 ERROR: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/node_6 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/node_6  && cd /tmp/dev-container-features/node_6  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/node_6]: exit code: 1#9 [internal] load metadata for mcr.microsoft.com/devcontainers/base:ubuntu
------
 > [dev_containers_target_stage  9/14] RUN --mount=type=bind,from=dev_containers_feature_content_source,source=node_6,target=/tmp/build-features-src/node_6     cp -ar /tmp/build-features-src/node_6 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/node_6  && cd /tmp/dev-container-features/node_6  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/node_6:
#21 9.390 Checksums matched!
#21 12.10 Now using node v18.16.0 (npm v9.5.1)
#21 12.24 Creating default alias: default -> lts/* (-> v18.16.0 *)
#21 12.33 => Node.js version lts/* has been successfully installed
#21 12.33 => Close and reopen your terminal to start using nvm or run the following to use it now:
#21 12.33 
#21 12.33 export NVM_DIR="/usr/local/share/nvm"
#21 12.33 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#21 12.61 zsh:8: no matches found: lts/*
#21 12.61 ERROR: Feature "Node.js (via nvm), yarn and pnpm" (ghcr.io/devcontainers/features/node) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/node for help troubleshooting this error.
------
ERROR: failed to solve: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/node_6 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/node_6  && cd /tmp/dev-container-features/node_6  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/node_6]: exit code: 1
{"outcome":"error","message":"Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.43.0-1686233476460 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-azdevcont-163ecb3852c7898f1345cb05d441b576057f682480f9d767efb2ddbff3e0c26d-features -f /tmp/devcontainercli-root/container-features/0.43.0-1686233476460/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder","description":"An error occurred setting up the container."}
Stop: Run: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.43.0-1686233476460 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-azdevcont-163ecb3852c7898f1345cb05d441b576057f682480f9d767efb2ddbff3e0c26d-features -f /tmp/devcontainercli-root/container-features/0.43.0-1686233476460/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.43.0-1686233476460 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-azdevcont-163ecb3852c7898f1345cb05d441b576057f682480f9d767efb2ddbff3e0c26d-features -f /tmp/devcontainercli-root/container-features/0.43.0-1686233476460/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
    at vte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2004:1066)
    at TN (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2004:1002)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Lte (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2021:[366](https://github.com/oliverlabs/azdevcont/actions/runs/5212210292/jobs/9405513410#step:4:367)0)
    at async Hf (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2021:4775)
    at async rne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2152:10[371](https://github.com/oliverlabs/azdevcont/actions/runs/5212210292/jobs/9405513410#step:4:372))
    at async tne (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2152:10112)
devcontainer process exited with exit code 1
Failed to create container.
Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.43.0-1686233476460 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/devcontainers/base:ubuntu --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-azdevcont-163ecb[385](https://github.com/oliverlabs/azdevcont/actions/runs/5212210292/jobs/9405513410#step:4:386)2c7898f1345cb05d[441](https://github.com/oliverlabs/azdevcont/actions/runs/5212210292/jobs/9405513410#step:4:442)b576057f682480f9d767efb2ddbff3e0c26d-features -f /tmp/devcontainercli-root/container-features/0.43.0-1686233476[460](https://github.com/oliverlabs/azdevcont/actions/runs/5212210292/jobs/9405513410#step:4:461)/Dockerfile.extended /var/lib/docker/codespacemount/.persistedshare/empty-folder
Error Code: 1302
Container creation failed.
Jobs failed, exiting the agent. Error Code: 1302
Error: Process completed with exit code 1.
```

**Comment by jkeech** [comment]
I'm not able to reproduce this. Here's the devcontainer I used for testing:

```json
{
  "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
  "features": {
    "ghcr.io/devcontainers/features/node:1": {}
  }
}
```

One thing that looks interesting to me in your error log is this part: `#21 12.61 zsh:8: no matches found: lts/*`. It's surprising that it's running in `zsh`, which is not the default shell in the image. My guess is that nvm in the feature is setting up the node config in the bash profile but not zsh, or at least the zsh is not being refreshed/sourced during the feature script execution, which is why the zsh subprocess cannot find the node version that was installed just before that.

What is setting `zsh` as the shell in your image? Can you share the full devcontainer.json config or a minimal repro example?

**Comment by oliverlabs** [comment]
Thanks so much for looking into it, John @jkeech. Indeed, I have zsh set as my default shell in my devcontainer, as I perefer it to bash (with oh-my-zsh). Is there any way to change the script to run on zsh?

Here's my [devcontainer.json](https://github.com/oliverlabs/azdevcont/blob/main/.devcontainer/devcontainer.json) file. 

Also, here's the bit where I am setting the remote shell:

```
	"remoteEnv": {
		"SHELL": "/usr/bin/zsh"
	},
```

**Comment by oliverlabs** [comment]
any ideas? @jkeech

**Comment by oliverlabs** [comment]
closing as there was no response.

**Comment by oliverlabs** [comment]
@jkeech, Hi John, could you please help me debug this to work on zsh?

**Comment by jkeech** [comment]
Hey, apologies I was out for a couple weeks on vacation. I'll take a look at this today.

**Comment by jkeech** [comment]
Thanks for sharing the devcontainer.json. This is indeed an issue with the `node` feature not working when ZSH is configured as the default shell through the `common-utils` feature. Here's a minimal repro devcontainer.json:

### Broken
```
{
    "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
    "features": {
        "ghcr.io/devcontainers/features/node:1": {},
        "ghcr.io/devcontainers/features/common-utils:2": {
            "CONFIGUREZSHASDEFAULTSHELL": true
        }
    }
}
```

Removing ` "CONFIGUREZSHASDEFAULTSHELL": true` fixes the issue.

### Working
```
{
    "image": "mcr.microsoft.com/devcontainers/base:ubuntu",
    "features": {
        "ghcr.io/devcontainers/features/node:1": {},
        "ghcr.io/devcontainers/features/common-utils:2": {}
    }
}
```

@samruddhikhandale it would be good to update the Node feature to work is ZSH is set as the default shell in the container before the node feature executes.

**Comment by oliverlabs** [comment]
Thanks so much, @jkeech . I can confirm that my devcontainer compiled successfully without the `CONFIGUREZSHASDEFAULTSHELL` option. I was even able to set zsh as a default shell using a different method via 

```bash
"remoteEnv": {
		"SHELL": "/usr/bin/zsh"
	}
```

**Comment by shikanime** [comment]
I have some believe that the root issue is because of the glob qualifier expansion at https://github.com/devcontainers/features/blob/f2594c5cc85e18450a31865f8387c8dc064006f2/src/node/install.sh#L163 that produce the error
```shell
#21 12.61 zsh:8: no matches found: lts/*
```
I can do this PR to correct the problem by quoting the argument because it's also best practice for this kind of thing to avoid too much script injection.

**Comment by oliverlabs** [comment]
Please do @shikanime

**Comment by oliverlabs** [comment]
Thanks so much for fixing it @shikanime. I can confirm that this now works as intended despite `"CONFIGUREZSHASDEFAULTSHELL": true` parameter present. Great catch!
