### ISSUE TITLE
docker-in-docker failing to build container 

### ISSUE THREAD

**Issue by ontoneio** [devcontainers/features#679]
I have created a reproduction repo of this issue. My project includes nx monorepo tooling, so that is included for posterity. 
Filed a related issue: https://github.com/devcontainers/cli/issues/629

https://github.com/ontoneio/dc-docker-in-docker-repro

When this repo run on WSL2 with dependencies install, USER can use `vscode` shortcut `shift + ctrl + p` and run `Dev Containers: Rebuild Without Cache and Reopen in Container`

These are the TAIL error logs

```
40.95 (Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 21144 files and directories currently installed.)

41.01 Preparing to unpack .../0-pigz_2.6-1_amd64.deb ...

41.02 Unpacking pigz (2.6-1) ...

41.05 Selecting previously unselected package libip4tc2:amd64.

41.05 Preparing to unpack .../1-libip4tc2_1.8.7-1ubuntu5.1_amd64.deb ...

41.06 Unpacking libip4tc2:amd64 (1.8.7-1ubuntu5.1) ...

41.09 Selecting previously unselected package libip6tc2:amd64.

41.09 Preparing to unpack .../2-libip6tc2_1.8.7-1ubuntu5.1_amd64.deb ...

41.09 Unpacking libip6tc2:amd64 (1.8.7-1ubuntu5.1) ...

41.11 Selecting previously unselected package libnfnetlink0:amd64.

41.12 Preparing to unpack .../3-libnfnetlink0_1.0.1-3build3_amd64.deb ...

41.12 Unpacking libnfnetlink0:amd64 (1.0.1-3build3) ...

41.15 Selecting previously unselected package libnetfilter-conntrack3:amd64.

41.15 Preparing to unpack .../4-libnetfilter-conntrack3_1.0.9-1_amd64.deb ...

41.15 Unpacking libnetfilter-conntrack3:amd64 (1.0.9-1) ...

41.18 Selecting previously unselected package libnftnl11:amd64.

41.18 Preparing to unpack .../5-libnftnl11_1.2.1-1build1_amd64.deb ...

41.18 Unpacking libnftnl11:amd64 (1.2.1-1build1) ...

41.20 Selecting previously unselected package iptables.

41.20 Preparing to unpack .../6-iptables_1.8.7-1ubuntu5.1_amd64.deb ...

41.21 Unpacking iptables (1.8.7-1ubuntu5.1) ...

41.25 Preparing to unpack .../7-apt-transport-https_2.4.10_all.deb ...

41.26 Unpacking apt-transport-https (2.4.10) over (2.4.9) ...

41.29 Setting up libip4tc2:amd64 (1.8.7-1ubuntu5.1) ...

41.30 Setting up apt-transport-https (2.4.10) ...

41.31 Setting up libip6tc2:amd64 (1.8.7-1ubuntu5.1) ...

41.32 Setting up libnftnl11:amd64 (1.2.1-1build1) ...

41.32 Setting up pigz (2.6-1) ...

41.33 Setting up libnfnetlink0:amd64 (1.0.1-3build3) ...

41.34 Setting up libnetfilter-conntrack3:amd64 (1.0.9-1) ...

41.35 Setting up iptables (1.8.7-1ubuntu5.1) ...

41.36 update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in auto mode

41.37 update-alternatives: using /usr/sbin/ip6tables-leg
[2023-08-30T20:46:17.975Z] acy to provide /usr/sbin/ip6tables (ip6tables) in auto mode

41.37 update-alternatives: using /usr/sbin/iptables-nft to provide /usr/sbin/iptables (iptables) in auto mode

41.37 update-alternatives: using /usr/sbin/ip6tables-nft to provide /usr/sbin/ip6tables (ip6tables) in auto mode

41.38 update-alternatives: using /usr/sbin/arptables-nft to provide /usr/sbin/arptables (arptables) in auto mode

41.38 update-alternatives: using /usr/sbin/ebtables-nft to provide /usr/sbin/ebtables (ebtables) in auto mode

41.38 Processing triggers for man-db (2.10.2-1) ...

41.49 Processing triggers for libc-bin (2.35-0ubuntu3.1) ...

41.56 update-alternatives: using /usr/sbin/iptables-legacy to provide /usr/sbin/iptables (iptables) in manual mode
41.56 update-alternatives: using /usr/sbin/ip6tables-legacy to provide /usr/sbin/ip6tables (ip6tables) in manual mode
41.56 MICROSOFT_GPG_KEYS_URI=https://packages.microsoft.com/keys/microsoft.asc
41.91 Get:1 https://packages.microsoft.com/repos/microsoft-ubuntu-jammy-prod jammy InRelease [3611 B]
41.96 Get:2 https://packages.microsoft.com/repos/microsoft-ubuntu-jammy-prod jammy/main all Packages [970 B]
41.98 Get:3 https://packages.microsoft.com/repos/microsoft-ubuntu-jammy-prod jammy/main amd64 Packages [88.7 kB]
42.12 Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
42.13 Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
42.43 Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
42.74 Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
42.79 Fetched 93.3 kB in 1s (94.3 kB/s)
42.79 Reading package lists...
44.32 (!) No full or partial Docker / Moby version match found for "2.4.0" on OS ubuntu jammy (amd64). Available versions:
44.80  23.0.6+azure-ubuntu22.04u2 
44.80  20.10.25+azure-ubuntu22.04u2 
44.80  20.10.25+azure-ubuntu22.04u1 
44.80  20.10.24+azure-ubuntu22.04u1 
44.80  20.10.23+azure-ubuntu22.04u2 
44.80  20.10.22+azure-ubuntu22.04u1 
44.80  20.10.21+azure-ubuntu22.04u2 
44.80  20.10.21+azure-ubuntu22.04u1 
44.80  20.10.20+azure-ubuntu22.04u1 
44.80  20.10.18+azure-ubuntu22.04u2 
44.80  20.10.18+azure-ubuntu22.04u1 
44.80  20.10.17+azure-ubuntu22.04u1 
44.80  20.10.15+azure-1 
44.80  20.10.14+azure-1 
44.80 ERROR: Feature "Docker (Docker-in-Docker)" (ghcr.io/devcontainers/features/docker-in-docker) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/docker-in-docker for help troubleshooting this error.
------
Dockerfile-with-features:98
--------------------
  97 |     ENV DOCKER_BUILDKIT="1"
  98 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=docker-in-docker_2,target=/tmp/build-features-src/docker-in-docker_2 \
  99 | >>>     cp -ar /tmp/build-features-src/docker-in-docker_2 /tmp/dev-container-features \
 100 | >>>  && chmod -R 0755 /tmp/dev-container-features/docker-in-docker_2 \
 101 | >>>  && cd /tmp/dev-container-features/docker-in-docker_2 \
 102 | >>>  && chmod +x ./devcontainer-features-install.sh \
 103 | >>>  && ./devcontainer-features-install.sh \
 104 | >>>  && rm -rf /tmp/dev-container-features/docker-in-docker_2
 105 |     
--------------------
ERROR: failed to solve: process "/bin/bash -c cp -ar /tmp/build-features-src/docker-in-docker_2 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/docker-in-docker_2  && cd /tmp/dev-container-features/docker-in-docker_2  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/docker-in-docker_2" did not complete successfully: exit code: 1
[2023-08-30T20:46:17.982Z] Stop (64276 ms): Run: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-vscode/container-features/0.50.0-1693428309819/Dockerfile-with-features -t vsc-dc-docker-in-docker-repro-cc19d46ee56ebd05eb801ce8f32784d99253a91f6dfe292989bad7f6d8fa5d1f --target dev_containers_target_stage --no-cache --pull --build-arg vscode=true --build-context dev_containers_feature_content_source=/tmp/devcontainercli-vscode/container-features/0.50.0-1693428309819 --build-arg _DEV_CONTAINERS_BASE_IMAGE=packaging --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/vscode/bug-repros/dc-docker-in-docker-repro
[2023-08-30T20:46:17.982Z] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f /tmp/devcontainercli-vscode/container-features/0.50.0-1693428309819/Dockerfile-with-features -t vsc-dc-docker-in-docker-repro-cc19d46ee56ebd05eb801ce8f32784d99253a91f6dfe292989bad7f6d8fa5d1f --target dev_containers_target_stage --no-cache --pull --build-arg vscode=true --build-context dev_containers_feature_content_source=/tmp/devcontainercli-vscode/container-features/0.50.0-1693428309819 --build-arg _DEV_CONTAINERS_BASE_IMAGE=packaging --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp /home/vscode/bug-repros/dc-docker-in-docker-repro
[2023-08-30T20:46:17.982Z]     at IAA (/home/vscode/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:463:1698)
[2023-08-30T20:46:17.982Z]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-08-30T20:46:17.982Z]     at async qw (/home/vscode/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:462:1691)
[2023-08-30T20:46:17.982Z]     at async mK (/home/vscode/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:462:610)
[2023-08-30T20:46:17.982Z]     at async mAA (/home/vscode/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2023-08-30T20:46:17.982Z]     at async LC (/home/vscode/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2023-08-30T20:46:17.982Z]     at async jeA (/home/vscode/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:611:12219)
[2023-08-30T20:46:17.982Z]     at async _eA (/home/vscode/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js:611:11960)
[2023-08-30T20:46:17.985Z] Stop (68972 ms): Run in Host: /home/vscode/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/vscode/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-b8d750e1-d721-4b51-8643-7c5299c1603e1693428306784 --workspace-folder /home/vscode/bug-repros/dc-docker-in-docker-repro --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-22.04\home\vscode\bug-repros\dc-docker-in-docker-repro --id-label devcontainer.config_file=/home/vscode/bug-repros/dc-docker-in-docker-repro/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vscode/bug-repros/dc-docker-in-docker-repro/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-08-30T20:46:17.985Z] Exit code 1
[2023-08-30T20:46:17.988Z] Command failed: /home/vscode/.vscode-server/bin/6c3e3dba23e8fadc360aed75ce363ba185c49794/node /home/vscode/.vscode-remote-containers/dist/dev-containers-cli-0.304.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-b8d750e1-d721-4b51-8643-7c5299c1603e1693428306784 --workspace-folder /home/vscode/bug-repros/dc-docker-in-docker-repro --workspace-mount-consistency cached --id-label devcontainer.local_folder=\\wsl.localhost\Ubuntu-22.04\home\vscode\bug-repros\dc-docker-in-docker-repro --id-label devcontainer.config_file=/home/vscode/bug-repros/dc-docker-in-docker-repro/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/vscode/bug-repros/dc-docker-in-docker-repro/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --build-no-cache --remove-existing-container --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[2023-08-30T20:46:17.988Z] Exit code 1
[2023-08-30T20:51:15.072Z] Start: Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\vscode\bug-repros\dc-docker-in-docker-repro
[2023-08-30T20:51:15.466Z] Stop (394 ms): Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\vscode\bug-repros\dc-docker-in-docker-repro

```

**Comment by ontoneio** [comment]
Closing as this seems to be an issue with `@devcontainers/cli`.

See issue [#629](https://github.com/devcontainers/cli/issues/629)
