### ISSUE TITLE
GPG Error with terraform feature

### ISSUE THREAD

**Issue by WTSParadigm** [devcontainers/features#716]
Just started getting the following error today, same devcontainer was working fine yesterday:

```
0.480 Running apt-get update...
0.644 Get:1 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]
0.673 Get:2 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
0.684 Get:3 http://deb.debian.org/debian buster InRelease [122 kB]
0.765 Get:4 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
0.791 Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [547 kB]
0.794 Get:6 https://packages.microsoft.com/repos/azure-cli buster InRelease [6479 B]
0.800 Err:2 https://dl.yarnpkg.com/debian stable InRelease
0.800   The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
0.878 Get:7 http://security.debian.org/debian-security buster/updates/non-free amd64 Packages [10.7 kB]
0.935 Get:8 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
1.051 Get:9 https://packages.microsoft.com/repos/azure-cli buster/main amd64 Packages [1014 B]
1.090 Get:10 https://packages.microsoft.com/repos/azure-cli buster/main all Packages [5053 B]
1.267 Get:11 http://deb.debian.org/debian buster/non-free amd64 Packages [87.8 kB]
1.338 Get:12 http://deb.debian.org/debian buster/contrib amd64 Packages [50.1 kB]
1.411 Get:13 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
2.205 Reading package lists...
2.801 W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures were invalid: EXPKEYSIG 23E7166788B63E1E Yarn Packaging <yarn@dan.cx>
2.801 E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
2.802 ERROR: Feature "Terraform, tflint, and TFGrunt" (ghcr.io/devcontainers/features/terraform) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/terr
aform for help troubleshooting this error.
------
Dockerfile.extended:42
--------------------
  41 |
  42 | >>> RUN --mount=type=bind,from=dev_containers_feature_content_source,source=terraform_2,target=/tmp/build-features-src/terraform_2 \
  43 | >>>     cp -ar /tmp/build-features-src/terraform_2 /tmp/dev-container-features \
  44 | >>>  && chmod -R 0755 /tmp/dev-container-features/terraform_2 \
  45 | >>>  && cd /tmp/dev-container-features/terraform_2 \
  46 | >>>  && chmod +x ./devcontainer-features-install.sh \
  47 | >>>  && ./devcontainer-features-install.sh \
  48 | >>>  && rm -rf /tmp/dev-container-features/terraform_2
  49 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cp -ar /tmp/build-features-src/terraform_2 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/terraform_2  && cd /tmp/dev-container-featur
es/terraform_2  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/terraform_2" did not complete successfully: exit code: 100
[46729 ms] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=C:\Users\<me>\AppData\Local\Temp\devcontainercli\container-features\0.51.3-1696532257541 --build-arg _DEV_CONTAINERS_BASE_IMAGE=mcr.microsoft.com/vscode/devcontainers/typescript-node:0-12 --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-app_comm_services-f1de11244bc6f02befcacaa543bae32c63ed1416a8df7889493d9ae9f78b82f5-features -f C:\Users\<me>\AppData\Local\Temp\devcontainercli\container-features\0.51.3-1696532257541\Dockerfile.extended c:\Users\<me>\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data\empty-folder
[46730 ms]     at IAA (c:\Users\<me>\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\spec-node\devContainersSpecCLI.js:462:1066)
[46730 ms]     at SK (c:\Users\<me>\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\spec-node\devContainersSpecCLI.js:462:1002)
[46730 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[46730 ms]     at async SAA (c:\Users\<me>\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\spec-node\devContainersSpecCLI.js:479:3660)
[46730 ms]     at async GC (c:\Users\<me>\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\spec-node\devContainersSpecCLI.js:479:4775)
[46730 ms]     at async ZeA (c:\Users\<me>\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\spec-node\devContainersSpecCLI.js:611:12251)
[46731 ms]     at async VeA (c:\Users\<me>\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\spec-node\devContainersSpecCLI.js:611:11992)
[46746 ms] Exit code 1
[46747 ms] Command failed: C:\Users\<me>\AppData\Local\Programs\Microsoft VS Code\Code.exe --ms-enable-electron-run-as-node c:\Users\<me>\.vscode\extensions\ms-vscode-remote.remote-containers-0.315.1\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\<me>\AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-e6072d6c-bf55-4455-81bc-6d9850f29ca51696532223145 --workspace-folder d:\projects\app_comm_services --workspace-mount-consistency cached --id-label devcontainer.local_folder=d:\projects\app_comm_services --id-label devcontainer.config_file=d:\projects\app_comm_services\.devcontainer\devcontainer.json --log-level debug --log-format json --config d:\projects\app_comm_services\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-20.04\run\user\1000\wayland-0,target=/tmp/vscode-wayland-7bb0c49c-a180-4631-bf52-12e3cdaf03eb.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --terminal-columns 205 --terminal-rows 20
[46748 ms] Exit code 1
```

My devcontainer.json file:
```
{
    "image": "mcr.microsoft.com/vscode/devcontainers/typescript-node:0-12",

    "name": "<Name>",

    "features": {
        "ghcr.io/devcontainers/features/azure-cli:1": {},
        "ghcr.io/devcontainers/features/terraform:1": {},
        "ghcr.io/devcontainers/features/git:1": {}
    },
    "runArgs": ["--init", "--env-file",".devcontainer/devcontainer.dev.env"],
    "remoteEnv": {
		// Sets environment variables required for terrafom remote backend
        "TF_BACKEND_SUBSCRIPTION_ID": "${containerEnv:TF_BACKEND_SUBSCRIPTION_ID}",
		"TF_BACKEND_RESOURCE_GROUP" : "${containerEnv:TF_BACKEND_RESOURCE_GROUP}",
		"TF_BACKEND_LOCATION": "${containerEnv:TF_BACKEND_LOCATION}",
		"TF_BACKEND_STORAGE_ACCOUNT" : "${containerEnv:TF_BACKEND_STORAGE_ACCOUNT}",                
		"TF_BACKEND_CONFIG_FILE_PATH" : "${containerEnv:TF_BACKEND_CONFIG_FILE_PATH}",
        "TF_PLAN_VARIABLES_FILE_PATH" : "${containerEnv:TF_PLAN_VARIABLES_FILE_PATH}",
        "TF_PREINFRA_BACKEND_CONFIG_FILE_PATH": "${containerEnv:TF_PREINFRA_BACKEND_CONFIG_FILE_PATH}",
        "TF_PREINFRA_PLAN_VARIABLES_FILE_PATH": "${containerEnv:TF_PREINFRA_PLAN_VARIABLES_FILE_PATH}",
        "TF_PROVISION_SUBSCRIPTION_ID" : "${containerEnv:TF_PROVISION_SUBSCRIPTION_ID}"
	},
    "customizations": {
        "vscode": {
            "extensions": ["dbaeumer.vscode-eslint"]
        }
    },
    "postCreateCommand": "chmod +x ./infrastructure/utils/*;cp ./infrastructure/utils/* /usr/local/bin",
    "forwardPorts": [3000]
}
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

Looks like you are running into https://github.com/devcontainers/images/issues/370 issue, I don't understand how it worked before as older images have been broken for a while.

Can you use one of the latest supported images? (eg. `mcr.microsoft.com/devcontainers/typescript-node:1-20`) See https://github.com/devcontainers/images/tree/main/src/typescript-node for more information.

**Comment by WTSParadigm** [comment]
Yeah using the latest image works, I'll just update. Thanks
