### ISSUE TITLE
[desktop-lite] Feature "Light-weight Desktop" (ghcr.io/devcontainers/features/desktop-lite) failed to install!

### ISSUE THREAD

**Issue by chase-sandmann-lyb** [devcontainers/features#728]
The desktop-lite plugin was installing perfectly fine in our devcontainer until about a week or so ago (Oct 11 was the first report).  The plugin stopped working with no configuration changes on our end.  This is the error we are receiving:

```
#0 80.84 Errors were encountered while processing:

#0 80.84  /tmp/apt-dpkg-install-XNTi4y/0-systemd_254.5-1_amd64.deb

#0 80.93 E: Sub-process /usr/bin/dpkg returned an error code (1)
#0 80.93 ERROR: Feature "Light-weight Desktop" (ghcr.io/devcontainers/features/desktop-lite) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/desktop-lite for help troubleshooting this error.
------
[2023-10-18T19:01:26.304Z] ERROR: failed to solve: executor failed running [/bin/sh -c cp -ar /tmp/build-features-src/desktop-lite_0 /tmp/dev-container-features  && chmod -R 0755 /tmp/dev-container-features/desktop-lite_0  && cd /tmp/dev-container-features/desktop-lite_0  && chmod +x ./devcontainer-features-install.sh  && ./devcontainer-features-install.sh  && rm -rf /tmp/dev-container-features/desktop-lite_0]: exit code: 100
[2023-10-18T19:01:26.313Z] Stop (82263 ms): Run: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/8c/cq9c3yyx53qb60531ct1b8w00000gn/T/devcontainercli/container-features/0.51.3-1697655600148 --build-arg _DEV_CONTAINERS_BASE_IMAGE=ghcr.io/lyb-digital-aa/dk-frontend-devcontainer:latest --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-c3-feo-ui-cdc3b811a1b769ce27865a3438d98778f215e2661849a3aa425680d5afc0d196-features -f /var/folders/8c/cq9c3yyx53qb60531ct1b8w00000gn/T/devcontainercli/container-features/0.51.3-1697655600148/Dockerfile.extended /Users/chasesandmann/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2023-10-18T19:01:26.313Z] Error: Command failed: docker buildx build --load --build-context dev_containers_feature_content_source=/var/folders/8c/cq9c3yyx53qb60531ct1b8w00000gn/T/devcontainercli/container-features/0.51.3-1697655600148 --build-arg _DEV_CONTAINERS_BASE_IMAGE=ghcr.io/lyb-digital-aa/dk-frontend-devcontainer:latest --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp --target dev_containers_target_stage -t vsc-c3-feo-ui-cdc3b811a1b769ce27865a3438d98778f215e2661849a3aa425680d5afc0d196-features -f /var/folders/8c/cq9c3yyx53qb60531ct1b8w00000gn/T/devcontainercli/container-features/0.51.3-1697655600148/Dockerfile.extended /Users/chasesandmann/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/empty-folder
[2023-10-18T19:01:26.313Z]     at IAA (/Users/chasesandmann/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:462:1066)
[2023-10-18T19:01:26.314Z]     at SK (/Users/chasesandmann/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:462:1002)
[2023-10-18T19:01:26.314Z]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[2023-10-18T19:01:26.314Z]     at async SAA (/Users/chasesandmann/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:479:3660)
[2023-10-18T19:01:26.314Z]     at async GC (/Users/chasesandmann/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:479:4775)
[2023-10-18T19:01:26.314Z]     at async ZeA (/Users/chasesandmann/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:611:12251)
[2023-10-18T19:01:26.314Z]     at async VeA (/Users/chasesandmann/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js:611:11992)
[2023-10-18T19:01:26.320Z] Stop (88684 ms): Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/chasesandmann/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/chasesandmann/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-60d080fc-6552-4c4d-a87e-fbcca4201b7b1697655596110 --workspace-folder /Users/chasesandmann/aa/c3-feo-ui --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/chasesandmann/aa/c3-feo-ui --id-label devcontainer.config_file=/Users/chasesandmann/aa/c3-feo-ui/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/chasesandmann/aa/c3-feo-ui/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-10-18T19:01:26.321Z] Exit code 1
[2023-10-18T19:01:26.323Z] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/chasesandmann/.vscode/extensions/ms-vscode-remote.remote-containers-0.315.1/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/chasesandmann/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-60d080fc-6552-4c4d-a87e-fbcca4201b7b1697655596110 --workspace-folder /Users/chasesandmann/aa/c3-feo-ui --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/chasesandmann/aa/c3-feo-ui --id-label devcontainer.config_file=/Users/chasesandmann/aa/c3-feo-ui/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/chasesandmann/aa/c3-feo-ui/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2023-10-18T19:01:26.323Z] Exit code 1
[2023-10-18T19:01:55.511Z] Error opening dev container configurations: CodeExpectedError: ENOPRO: No file system provider found for resource 'vscode-remote://dev-container%2B7b22686f737450617468223a222f55736572732f636861736573616e646d616e6e2f61612f63332d66656f2d7569222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f636861736573616e646d616e6e2f61612f63332d66656f2d75692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f636861736573616e646d616e6e2f61612f63332d66656f2d75692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f636861736573616e646d616e6e2f61612f63332d66656f2d75692f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d/workspaces/c3-feo-ui'
    at r.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:645:11397)
    at async r.exists (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:645:13603)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1861:2796
```

We didn't change anything in terms of our devcontainer or docker image configuration, so we have no leads on how to resolve this.  Did something change on the devcontainer side?

**Comment by jkeech** [comment]
> #0 80.84 Errors were encountered while processing:
> 
> #0 80.84  /tmp/apt-dpkg-install-XNTi4y/0-systemd_254.5-1_amd64.deb
> 
> #0 80.93 E: Sub-process /usr/bin/dpkg returned an error code (1)

Can you share the logs that happened before this? The error message is saying that the dpkg install of som package (systemd) failed. The actual error from dpkg is probably above the section that is shared currently.

Can you provide a minimal devcontainer.json that we can use to reproduce the error?

**Comment by chase-sandmann-lyb** [comment]
Here is the relevant configuration we are using in our `devcontainer.json`:
```
  "features": {
    "ghcr.io/devcontainers/features/desktop-lite:1": {
      /* This is unfortunately required at the moment */
      "password": "vscode"
    }
  },
  "forwardPorts": [6080, 5901],
  "portsAttributes": {
    "6080": {
      "label": "desktop"
    }
  },
```

And this is the log file (which is quite large):

[remoteContainers-2023-10-18T18-59-56.778Z.log](https://github.com/devcontainers/features/files/13034674/remoteContainers-2023-10-18T18-59-56.778Z.log)

**Comment by jkeech** [comment]
From the full logs, it looks like systemd/udev are already installed with a different version before the desktop-lite script installs newer versions, and the old version is somehow conflicting with the new version. Could you try uninstalling systemd/udev in your base image before the feature install script runs?

```
#0 79.65 Preparing to unpack .../0-systemd_254.5-1_amd64.deb ...
[2023-10-18T19:01:26.304Z] 
#0 79.74 Unpacking systemd (254.5-1) over (247.3-7+deb11u4) ...

#0 79.95 dpkg: error processing archive /tmp/apt-dpkg-install-XNTi4y/0-systemd_254.5-1_amd64.deb (--unpack):

#0 79.95  trying to overwrite '/lib/systemd/system/systemd-hwdb-update.service', which is also in package udev 247.3-7+deb11u4

#0 79.95 dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
```

**Comment by chase-sandmann-lyb** [comment]
It took a while to narrow this down because we never directly install `systemd` or `udev` - they aren't mentioned anywhere in our repo.  The offending package was `chromium` which we need to run our unit tests.  Removing this would be a complete headache if there is even an alternative.

Shouldn't this feature check whether or not this package is already installed before trying to install it again?  I'm not exactly sure what the solution should be, but if we can't use this feature and `chromium` at the same time, that is a non-starter for our use case.
