### ISSUE TITLE
devcontainer with docker-in-docker feature doesn't work for any of 2.10.*

### ISSUE THREAD

**Issue by dsuhinin** [devcontainers/features#900]
Im using the latest `docker-in-docker`:
```
"ghcr.io/devcontainers/features/docker-in-docker:2": {
			"dockerDashComposeVersion": "none"
}
```
When Im trying to run my `devcontainer` I can see next error:
```
failed to solve: process "/bin/sh -c chmod -R 0755 /tmp/dev-container-features/docker-in-docker_1 && cd /tmp/dev-container-features/docker-in-docker_1 && chmod +x ./devcontainer-features-install.sh && ./devcontainer-features-install.sh" did not complete successfully: exit code: 2
[47053 ms] Error: Command failed: docker-compose --project-name fasttrack_devcontainer -f /Users/dsuhinin/Work/Projects/GR/fasttrack/src/github.com/G-Research/fasttrack/.devcontainer/docker-compose.yml -f /Users/dsuhinin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data/docker-compose/docker-compose.devcontainer.build-1709807676285.yml build
[47054 ms]     at Tw (/Users/dsuhinin/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:427:409)
[47054 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[47054 ms]     at async tAA (/Users/dsuhinin/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:427:2378)
[47054 ms]     at async eAA (/Users/dsuhinin/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:409:3167)
[47054 ms]     at async FAA (/Users/dsuhinin/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:3833)
[47054 ms]     at async GC (/Users/dsuhinin/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:479:4775)
[47054 ms]     at async VeA (/Users/dsuhinin/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:12240)
[47054 ms]     at async WeA (/Users/dsuhinin/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js:611:11981)
[47059 ms] Exit code 1
[47062 ms] Command failed: /private/var/folders/kk/0r187wtn06d_kdzq6cp_fhb40000gn/T/AppTranslocation/2C1863D0-E0CD-4ABC-A453-3C2A63C7B9C5/d/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/dsuhinin/.vscode/extensions/ms-vscode-remote.remote-containers-0.309.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/dsuhinin/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-23145f52-bb69-45c1-a253-4dbc9dbd6ea51709807665206 --workspace-folder /Users/dsuhinin/Work/Projects/GR/fasttrack/src/github.com/G-Research/fasttrack --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/dsuhinin/Work/Projects/GR/fasttrack/src/github.com/G-Research/fasttrack --id-label devcontainer.config_file=/Users/dsuhinin/Work/Projects/GR/fasttrack/src/github.com/G-Research/fasttrack/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/dsuhinin/Work/Projects/GR/fasttrack/src/github.com/G-Research/fasttrack/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[47063 ms] Exit code 1
```

I tried to run my `devcontainer` with other 2.10.* versions but result is the same until I switch back to `2.9` which works for me without any problem.

**Comment by samruddhikhandale** [comment]
Hi 👋 

I was not able to reproduce the issue, look at the screenshot below

![Image](https://github.com/devcontainers/features/assets/24955913/38679f7e-34a8-45c5-9f39-6fef2e1912b3)

@dsuhinin Can you paste the complete creation logs for your dev container? Also, can you share a sample dev container so that I can try reproducing the issue, thanks!

**Comment by samruddhikhandale** [comment]
Thanks for providing a repro. To me, it looks like an issue with the combination of `nfcore/gitpod:dev` image with `docker-in-docker` Feature which seems to somehow break the Codespace connection. This is interesting and a dev container config should not be responsible to break a codespace connection.

I'll forward this to the Codespaces team for a closer look, will keep you posted. Thanks! 

In the meanwhile, @mashehu  you should be able to get things in a working state if you pin the `docker-in-docker` Feature or use some other image.

**Comment by neverset123** [comment]
same here, changing to `"features": {
        "ghcr.io/devcontainers/features/docker-in-docker:2.9": {}
    },` fixed the problem
