### ISSUE TITLE
docker-in-docker : Failure loading feature - TypeError: Cannot convert object to primitive value

### ISSUE THREAD

**Issue by gitautas** [devcontainers/features#966]
When trying to build my project I get the following output:
```sh
[2024-05-10T20:04:37.569Z] Dev Containers 0.365.0 over Remote - SSH 0.110.1 in VS Code 1.90.0-insider (1facdf8117ba7aa833fa90539414e310a581e74c).
[2024-05-10T20:04:37.569Z] Start: Resolving Remote
[2024-05-10T20:04:37.574Z] Host OS: linux 6.6.0-14-generic
[2024-05-10T20:04:37.574Z] Host CWD: /home/dripauskaite/veil
[2024-05-10T20:04:37.574Z] Start: Run: /bin/sh 
[2024-05-10T20:04:37.580Z] Start: Run in host: echo ~
[2024-05-10T20:04:37.624Z] /home/dripauskaite
[2024-05-10T20:04:37.624Z] 
[2024-05-10T20:04:37.624Z] Stop (44 ms): Run in host: echo ~
[2024-05-10T20:04:37.624Z] Start: Run in host: id -un
[2024-05-10T20:04:37.673Z] dripauskaite
[2024-05-10T20:04:37.673Z] 
[2024-05-10T20:04:37.673Z] Stop (49 ms): Run in host: id -un
[2024-05-10T20:04:37.673Z] Start: Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'dripauskaite' || grep -E '^dripauskaite|^[^:]*:[^:]*:dripauskaite:' /etc/passwd || true)
[2024-05-10T20:04:37.722Z] Stop (49 ms): Run in host:  (command -v getent >/dev/null 2>&1 && getent passwd 'dripauskaite' || grep -E '^dripauskaite|^[^:]*:[^:]*:dripauskaite:' /etc/passwd || true)
[2024-05-10T20:04:37.723Z] userEnvProbe: loginInteractiveShell (default)
[2024-05-10T20:04:37.723Z] userEnvProbe: not found in cache
[2024-05-10T20:04:37.724Z] userEnvProbe shell: /usr/bin/zsh
[2024-05-10T20:04:37.847Z] userEnvProbe PATHs:
Probe:     '/home/dripauskaite/.local/share/pnpm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
Container: None
[2024-05-10T20:04:37.853Z] Setting up container for folder or workspace: /home/dripauskaite/veil
[2024-05-10T20:04:37.854Z] Host authority: ssh-remote+uwu
[2024-05-10T20:04:37.857Z] Start: Check Docker is running
[2024-05-10T20:04:37.857Z] Start: Run: docker version
[2024-05-10T20:04:37.908Z] Client: Docker Engine - Community
[2024-05-10T20:04:37.909Z]  Version:           25.0.3
[2024-05-10T20:04:37.909Z] 
 API version:       1.44
 Go version:
[2024-05-10T20:04:37.910Z]         go1.21.6
 Git commit:        4debf41
 Built:
[2024-05-10T20:04:37.910Z]              Tue Feb  6 21:14:22 2024
 OS/Arch:
[2024-05-10T20:04:37.910Z]            linux/amd64
[2024-05-10T20:04:37.910Z] 
 Context:           default

[2024-05-10T20:04:37.910Z] Server: Docker Engine - Community
[2024-05-10T20:04:37.910Z]  Engine:
[2024-05-10T20:04:37.910Z]   Version:          25.0.3
[2024-05-10T20:04:37.911Z]   API version:      1.44 (minimum version 1.24)
  Go version:
[2024-05-10T20:04:37.911Z]        go1.21.6
  Git commit:       
[2024-05-10T20:04:37.911Z] f417435
  Built:        
[2024-05-10T20:04:37.911Z]     Tue Feb  6 21:14:22 2024
  OS/Arch:        
[2024-05-10T20:04:37.911Z]   linux/amd64
  Experimental:
[2024-05-10T20:04:37.911Z]      false
 containerd:
[2024-05-10T20:04:37.912Z]   Version:          
[2024-05-10T20:04:37.912Z] 1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
[2024-05-10T20:04:37.912Z] 
 nvidia:
[2024-05-10T20:04:37.912Z]   Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[2024-05-10T20:04:37.912Z] Stop (55 ms): Run: docker version
[2024-05-10T20:04:37.913Z] Stop (56 ms): Check Docker is running
[2024-05-10T20:04:37.915Z] Start: Run: docker volume ls -q
[2024-05-10T20:04:37.971Z] Stop (56 ms): Run: docker volume ls -q
[2024-05-10T20:04:37.972Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/home/dripauskaite/veil --filter label=vsch.quality=insider
[2024-05-10T20:04:38.038Z] Stop (66 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/home/dripauskaite/veil --filter label=vsch.quality=insider
[2024-05-10T20:04:38.039Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dripauskaite/veil --filter label=devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json
[2024-05-10T20:04:38.105Z] Stop (66 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dripauskaite/veil --filter label=devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json
[2024-05-10T20:04:38.105Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dripauskaite/veil
[2024-05-10T20:04:38.161Z] Stop (56 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dripauskaite/veil
[2024-05-10T20:04:38.161Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dripauskaite/veil
[2024-05-10T20:04:38.218Z] Stop (57 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dripauskaite/veil
[2024-05-10T20:04:38.219Z] Running Dev Containers CLI:   read-configuration --workspace-folder /home/dripauskaite/veil --id-label devcontainer.local_folder=/home/dripauskaite/veil --id-label devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/dripauskaite/veil/.devcontainer/devcontainer.json --mount-workspace-git-root
[2024-05-10T20:04:38.227Z] Start: Run: /home/dripauskaite/.vscode-server-insiders/cli/servers/Insiders-1facdf8117ba7aa833fa90539414e310a581e74c/server/node /home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/dripauskaite/veil --id-label devcontainer.local_folder=/home/dripauskaite/veil --id-label devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/dripauskaite/veil/.devcontainer/devcontainer.json --mount-workspace-git-root
[2024-05-10T20:04:38.822Z] @devcontainers/cli 0.60.0. Node.js v18.18.2. linux 6.6.0-14-generic x64.
[2024-05-10T20:04:38.821Z] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dripauskaite/veil --filter label=devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json
[2024-05-10T20:04:38.840Z] Stop (19 ms): Run: docker ps -q -a --filter label=devcontainer.local_folder=/home/dripauskaite/veil --filter label=devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json
[2024-05-10T20:04:38.499Z] Stop (272 ms): Run: /home/dripauskaite/.vscode-server-insiders/cli/servers/Insiders-1facdf8117ba7aa833fa90539414e310a581e74c/server/node /home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /home/dripauskaite/veil --id-label devcontainer.local_folder=/home/dripauskaite/veil --id-label devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/dripauskaite/veil/.devcontainer/devcontainer.json --mount-workspace-git-root
[2024-05-10T20:04:38.499Z] Running Dev Containers CLI:   up --container-session-data-folder /tmp/devcontainers-9585d047-1ca3-4f8b-a56d-f46cd35790321715371477171 --workspace-folder /home/dripauskaite/veil --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/dripauskaite/veil --id-label devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/dripauskaite/veil/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-05-10T20:04:38.504Z] Start: Run: /home/dripauskaite/.vscode-server-insiders/cli/servers/Insiders-1facdf8117ba7aa833fa90539414e310a581e74c/server/node /home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-9585d047-1ca3-4f8b-a56d-f46cd35790321715371477171 --workspace-folder /home/dripauskaite/veil --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/dripauskaite/veil --id-label devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/dripauskaite/veil/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-05-10T20:04:39.069Z] @devcontainers/cli 0.60.0. Node.js v18.18.2. linux 6.6.0-14-generic x64.
[2024-05-10T20:04:39.069Z] Start: Run: docker buildx version
[2024-05-10T20:04:39.124Z] Stop (55 ms): Run: docker buildx version
[2024-05-10T20:04:39.124Z] github.com/docker/buildx v0.12.1 30feaa1
[2024-05-10T20:04:39.124Z] 
[2024-05-10T20:04:39.124Z] Start: Run: docker -v
[2024-05-10T20:04:39.137Z] Stop (13 ms): Run: docker -v
[2024-05-10T20:04:39.137Z] Start: Resolving Remote
[2024-05-10T20:04:39.143Z] Start: Run: docker-compose version --short
[2024-05-10T20:04:39.146Z] Stop (3 ms): Run: docker-compose version --short
[2024-05-10T20:04:39.146Z] Start: Run: docker compose version --short
[2024-05-10T20:04:39.149Z] Stop (6 ms): Run: docker-compose version --short
[2024-05-10T20:04:39.195Z] Stop (49 ms): Run: docker compose version --short
[2024-05-10T20:04:39.196Z] Docker Compose version: 2.24.5
[2024-05-10T20:04:39.196Z] Start: Run: docker compose -f /home/dripauskaite/veil/.devcontainer/compose.yml --profile * config
[2024-05-10T20:04:39.250Z] Stop (54 ms): Run: docker compose -f /home/dripauskaite/veil/.devcontainer/compose.yml --profile * config
[2024-05-10T20:04:39.250Z] name: devcontainer
services:
  veil-dev:
    build:
      context: /home/dripauskaite/veil/.devcontainer
      dockerfile: Dockerfile
    container_name: veil-dev
    networks:
      default: null
    volumes:
      - type: bind
        source: /home/dripauskaite/veil
        target: /workspace
        bind:
          create_host_path: true
networks:
  default:
    name: devcontainer_default
[2024-05-10T20:04:39.253Z] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=devcontainer --filter label=com.docker.compose.service=veil-dev
[2024-05-10T20:04:39.269Z] Stop (16 ms): Run: docker ps -q -a --filter label=com.docker.compose.project=devcontainer --filter label=com.docker.compose.service=veil-dev
[2024-05-10T20:04:39.270Z] Start: Run: docker events --format {{json .}} --filter event=start
[2024-05-10T20:04:39.273Z] PersistedPath=/tmp/devcontainercli-dripauskaite, ContainerHasLabels=false
[2024-05-10T20:04:39.274Z] Start: Run: docker compose -f /home/dripauskaite/veil/.devcontainer/compose.yml --profile * config
[2024-05-10T20:04:39.335Z] Stop (61 ms): Run: docker compose -f /home/dripauskaite/veil/.devcontainer/compose.yml --profile * config
[2024-05-10T20:04:39.335Z] name: devcontainer
services:
  veil-dev:
    build:
      context: /home/dripauskaite/veil/.devcontainer
      dockerfile: Dockerfile
    container_name: veil-dev
    networks:
      default: null
    volumes:
      - type: bind
        source: /home/dripauskaite/veil
        target: /workspace
        bind:
          create_host_path: true
networks:
  default:
    name: devcontainer_default
[2024-05-10T20:04:39.337Z] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:noble
[2024-05-10T20:04:39.353Z] Stop (16 ms): Run: docker inspect --type image mcr.microsoft.com/devcontainers/base:noble
[2024-05-10T20:04:40.333Z] Resolving Feature dependencies for 'ghcr.io/devcontainers/features/docker-in-docker:2'...
[2024-05-10T20:04:40.334Z] * Processing feature: ghcr.io/devcontainers/features/docker-in-docker:2
[2024-05-10T20:04:40.571Z] Start: Run: docker-credential-secret get
[2024-05-10T20:04:40.584Z] Stop (13 ms): Run: docker-credential-secret get
[2024-05-10T20:04:40.591Z] Stop (20 ms): Run: docker-credential-secret get
[2024-05-10T20:04:41.098Z] * Processing feature: ghcr.io/devcontainers/features/common-utils
[2024-05-10T20:04:41.374Z] Soft-dependency 'ghcr.io/devcontainers/features/common-utils' is not required.  Removing from installation order...
[2024-05-10T20:04:41.378Z] * Fetching feature: docker-in-docker_0_oci
[2024-05-10T20:04:41.784Z] * Fetched feature: docker-in-docker_0_oci version 2.10.2
[2024-05-10T20:04:41.437Z] TypeError: Cannot convert object to primitive value
[2024-05-10T20:04:41.438Z]     at /home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js:409:1058
[2024-05-10T20:04:41.438Z]     at Array.map (<anonymous>)
[2024-05-10T20:04:41.438Z]     at Gm (/home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js:409:1037)
[2024-05-10T20:04:41.438Z]     at atA (/home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js:403:193)
[2024-05-10T20:04:41.438Z]     at async VC (/home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js:392:2380)
[2024-05-10T20:04:41.438Z]     at async Km (/home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js:409:5265)
[2024-05-10T20:04:41.439Z]     at async QtA (/home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js:429:2476)
[2024-05-10T20:04:41.439Z]     at async utA (/home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js:409:3506)
[2024-05-10T20:04:41.439Z]     at async KtA (/home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js:481:3865)
[2024-05-10T20:04:41.440Z]     at async AB (/home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js:481:4807)
[2024-05-10T20:04:41.447Z] Stop (2943 ms): Run: /home/dripauskaite/.vscode-server-insiders/cli/servers/Insiders-1facdf8117ba7aa833fa90539414e310a581e74c/server/node /home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-9585d047-1ca3-4f8b-a56d-f46cd35790321715371477171 --workspace-folder /home/dripauskaite/veil --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/dripauskaite/veil --id-label devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/dripauskaite/veil/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-05-10T20:04:41.448Z] Exit code 1
[2024-05-10T20:04:41.457Z] Command failed: /home/dripauskaite/.vscode-server-insiders/cli/servers/Insiders-1facdf8117ba7aa833fa90539414e310a581e74c/server/node /home/dripauskaite/.vscode-remote-containers/dist/dev-containers-cli-0.365.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-9585d047-1ca3-4f8b-a56d-f46cd35790321715371477171 --workspace-folder /home/dripauskaite/veil --workspace-mount-consistency cached --id-label devcontainer.local_folder=/home/dripauskaite/veil --id-label devcontainer.config_file=/home/dripauskaite/veil/.devcontainer/devcontainer.json --log-level debug --log-format json --config /home/dripauskaite/veil/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[2024-05-10T20:04:41.457Z] Exit code 1
```

Here's my `devcontainer.json`:

```json
{
	"name": "veil-dev",
	"dockerComposeFile": "compose.yml",
	"service": "veil-dev",
	"workspaceFolder": "/workspace",
	"remoteUser": "dev",
	"features": {
		"ghcr.io/devcontainers/features/docker-in-docker:2": {
			"options": { "moby": false }
		}
	}
}
```

Here's my `compose.yml`:
```yaml
version: '3'
services:
  veil-dev:
    container_name: veil-dev
    build:
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
```
and here's my `Dockerfile`:

```dockerfile
FROM mcr.microsoft.com/devcontainers/base:noble

RUN usermod -l dev -d /home/dev -m vscode \
    && usermod -aG sudo dev \
    && echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

USER dev```

I'm using Visual Studio Code - Insiders `1.90.0-insider (Universal)` on MacOS Sonoma `14.3`
Connected to an SSH host running `Ubuntu 24.04` with `Docker version 25.0.3, build 4debf41`.

**Comment by samruddhikhandale** [comment]
Hi 👋 

> * Fetched feature: docker-in-docker_0_oci version 2.10.2
[2024-05-10T20:04:41.437Z] TypeError: Cannot convert object to primitive value

The `devcontainer.json` doesn't seem right to me, which is causing ^ errors. Can you test again with the following config?

```
{
	"name": "veil-dev",
	"dockerComposeFile": "compose.yml",
	"service": "veil-dev",
	"workspaceFolder": "/workspace",
	"remoteUser": "dev",
	"features": {
		"ghcr.io/devcontainers/features/docker-in-docker:2": {
			"moby": false
		}
	}
}
```
